/* ============================================================
   data.js  —  Subject → Topic → Question Bank
   ============================================================ */

const QUESTION_BANK = {

  // ══════════════════════════════════════════════════════════
  // PHYSICS
  // ══════════════════════════════════════════════════════════
  Physics: {
    icon: '⚡',
    topics: {

      'Kinematics': [
        {
          question: 'A ball is thrown horizontally at 20 m/s from a height of 80 m. Its horizontal range is (g = 10 m/s²):',
          optA: '40 m', optB: '60 m', optC: '80 m', optD: '100 m',
          hint1: 'First find time to fall: use h = ½gt².',
          hint2: 't = √(2×80/10) = 4 s.',
          hint3: 'Range = horizontal speed × time = 20 × 4 = 80 m.',
          answer: 'C', level: 1,
        },
        {
          question: 'A body starts from rest with uniform acceleration 4 m/s². Distance covered in the 5th second is:',
          optA: '10 m', optB: '14 m', optC: '16 m', optD: '18 m',
          hint1: 'Use the formula for distance in nth second: s_n = u + a(n − ½).',
          hint2: 'u = 0, a = 4, n = 5.',
          hint3: 's₅ = 0 + 4×(4.5) = 18 m.',
          answer: 'D', level: 1,
        },
        {
          question: 'Train A moves east at 60 km/h; Train B moves west at 90 km/h. Speed of B relative to A:',
          optA: '30 km/h', optB: '90 km/h', optC: '150 km/h', optD: '60 km/h',
          hint1: 'Opposite directions → relative speeds add.',
          hint2: 'v_rel = v_B + v_A (magnitudes for opposite directions).',
          hint3: '60 + 90 = 150 km/h.',
          answer: 'C', level: 1,
        },
        {
          question: 'A projectile is launched at 45°. If maximum height is H, the range R equals:',
          optA: 'H', optB: '2H', optC: '3H', optD: '4H',
          hint1: 'Express both H and R in terms of initial speed u and g.',
          hint2: 'H = u²sin²45°/2g = u²/4g; R = u²sin90°/g = u²/g.',
          hint3: 'R/H = 4, so R = 4H.',
          answer: 'D', level: 2,
        },
        {
          question: 'A v–t graph: velocity increases linearly from 0 to 20 m/s over 5 s, remains constant for 3 s, then decreases to 0 in 2 s. Total distance covered:',
          optA: '110 m', optB: '120 m', optC: '130 m', optD: '140 m',
          hint1: 'Distance = area under v–t graph.',
          hint2: 'Three regions: triangle (0–5 s), rectangle (5–8 s), triangle (8–10 s).',
          hint3: '½×5×20 + 20×3 + ½×2×20 = 50 + 60 + 20 = 130 m.',
          answer: 'C', level: 3,
        },
      ],

      'Laws of Motion': [
        {
          question: 'An Atwood machine has m₁ = 3 kg and m₂ = 5 kg. Acceleration of the system (g = 10 m/s²):',
          optA: '1.25 m/s²', optB: '2.5 m/s²', optC: '5 m/s²', optD: '10 m/s²',
          hint1: 'Net force = (m₂ − m₁)g; total mass = m₁ + m₂.',
          hint2: 'a = (m₂ − m₁)g / (m₁ + m₂).',
          hint3: 'a = (2×10)/8 = 2.5 m/s².',
          answer: 'B', level: 1,
        },
        {
          question: 'A lift accelerates upward at 2 m/s². Apparent weight of a 60 kg passenger (g = 10 m/s²):',
          optA: '480 N', optB: '600 N', optC: '720 N', optD: '840 N',
          hint1: 'For upward acceleration: apparent weight = m(g + a).',
          hint2: 'W = 60 × (10 + 2).',
          hint3: 'W = 60 × 12 = 720 N.',
          answer: 'C', level: 1,
        },
        {
          question: 'A block (m = 2 kg) is pressed against a wall by horizontal force F = 60 N (μs = 0.4, g = 10). The friction force on the block is:',
          optA: '20 N upward', optB: '24 N upward', optC: 'Block slides down', optD: '60 N',
          hint1: 'Normal force from wall = F = 60 N. Static friction acts upward to balance weight.',
          hint2: 'Max static friction = μs × N = 0.4 × 60 = 24 N; Weight = 20 N.',
          hint3: '24 N > 20 N, so block is in equilibrium. Actual friction = 20 N (equals weight).',
          answer: 'A', level: 2,
        },
        {
          question: 'A 4 kg block on a smooth table is connected via a string over a pulley to two hanging masses: m₂ = 2 kg, and m₃ = 1 kg hanging from m₂. Acceleration of system (g = 10):',
          optA: '30/7 m/s²', optB: '10/3 m/s²', optC: '5 m/s²', optD: '3 m/s²',
          hint1: 'Only hanging masses (m₂ + m₃) drive the system.',
          hint2: 'Net force = (m₂ + m₃)g = 3 × 10 = 30 N; total mass = 4 + 2 + 1 = 7 kg.',
          hint3: 'a = 30/7 ≈ 4.3 m/s².',
          answer: 'A', level: 2,
        },
        {
          question: 'A block (5 kg) on a rough incline (θ = 30°, μ = 0.4) — minimum force parallel to the incline to push it UP (g = 10):',
          optA: '25 N', optB: '32 N', optC: '42.3 N', optD: '50 N',
          hint1: 'Force needed = component of gravity along incline + friction force (both oppose upward motion).',
          hint2: 'F = mg sinθ + μmg cosθ = mg(sinθ + μcosθ).',
          hint3: 'F = 5×10×(0.5 + 0.4×0.866) = 50×0.846 ≈ 42.3 N.',
          answer: 'C', level: 3,
        },
      ],

      'Work, Energy & Power': [
        {
          question: 'A spring (k = 200 N/m) is compressed by 10 cm. Energy stored:',
          optA: '0.5 J', optB: '1 J', optC: '2 J', optD: '4 J',
          hint1: 'Elastic PE = ½kx².',
          hint2: 'x = 0.1 m, k = 200 N/m.',
          hint3: 'U = ½ × 200 × 0.01 = 1 J.',
          answer: 'B', level: 1,
        },
        {
          question: 'A 4 kg ball falls from 5 m and bounces to 3.2 m. Energy lost to heat (g = 10):',
          optA: '32 J', optB: '56 J', optC: '72 J', optD: '128 J',
          hint1: 'Energy lost = change in potential energy (starts and ends at rest).',
          hint2: 'ΔE = mg(h₁ − h₂).',
          hint3: 'ΔE = 4 × 10 × (5 − 3.2) = 72 J.',
          answer: 'C', level: 1,
        },
        {
          question: 'A force F = (20 − 4x) N acts on a body. Work done from x = 0 to x = 4 m:',
          optA: '32 J', optB: '40 J', optC: '48 J', optD: '56 J',
          hint1: 'W = ∫F dx when force varies with position.',
          hint2: 'W = ∫₀⁴(20 − 4x) dx = [20x − 2x²]₀⁴.',
          hint3: '= (80 − 32) − 0 = 48 J.',
          answer: 'C', level: 2,
        },
        {
          question: 'A ball hits a wall at 10 m/s and bounces back at 8 m/s. Coefficient of restitution e:',
          optA: '0.6', optB: '0.75', optC: '0.8', optD: '0.9',
          hint1: 'e = relative speed after collision / relative speed before collision.',
          hint2: 'Wall is stationary, so e = speed of rebound / speed of approach.',
          hint3: 'e = 8/10 = 0.8.',
          answer: 'C', level: 2,
        },
        {
          question: 'A particle (2 kg) moves under potential U = (x² − 4x) J. Its equilibrium position and nature:',
          optA: 'x = 2 m, stable', optB: 'x = 2 m, unstable', optC: 'x = 4 m, stable', optD: 'x = 0, neutral',
          hint1: 'At equilibrium, F = −dU/dx = 0.',
          hint2: '−dU/dx = −(2x − 4) = 0 → x = 2 m.',
          hint3: 'd²U/dx² = 2 > 0 (potential minimum) → stable equilibrium.',
          answer: 'A', level: 3,
        },
      ],

      'Electrostatics': [
        {
          question: 'Two charges of +3 µC each are separated by 3 cm. Force between them (k = 9×10⁹):',
          optA: '30 N', optB: '60 N', optC: '90 N', optD: '120 N',
          hint1: 'Use Coulomb\'s law: F = kq₁q₂/r².',
          hint2: 'q₁ = q₂ = 3×10⁻⁶ C, r = 0.03 m.',
          hint3: 'F = 9×10⁹ × 9×10⁻¹² / 9×10⁻⁴ = 90 N.',
          answer: 'C', level: 1,
        },
        {
          question: 'An electron accelerated through 100 V gains kinetic energy of (e = 1.6×10⁻¹⁹ C):',
          optA: '1.6×10⁻¹⁹ J', optB: '1.6×10⁻¹⁷ J', optC: '1.6×10⁻²¹ J', optD: '100 J',
          hint1: 'Work done on a charge = |q|ΔV.',
          hint2: 'KE gained = eV = 1.6×10⁻¹⁹ × 100.',
          hint3: 'KE = 1.6×10⁻¹⁷ J = 100 eV.',
          answer: 'B', level: 1,
        },
        {
          question: 'A parallel plate capacitor (area A, separation d) has a dielectric slab (thickness t, constant K) inserted. New capacitance:',
          optA: 'ε₀A/(d − t + t/K)', optB: 'Kε₀A/d', optC: 'ε₀A/d', optD: 'Kε₀A/(d−t)',
          hint1: 'The slab splits the gap into two regions in series: air (d−t) and dielectric (t).',
          hint2: '1/C = (d−t)/(ε₀A) + t/(Kε₀A).',
          hint3: 'C = ε₀A/(d − t + t/K).',
          answer: 'A', level: 2,
        },
        {
          question: 'A spherical conductor of radius R carries charge Q. Which statement about E vs r is correct?',
          optA: 'E increases linearly inside, then decreases as 1/r² outside',
          optB: 'E = 0 inside, maximum at surface, decreases as 1/r² outside',
          optC: 'E is uniform everywhere',
          optD: 'E increases as r² inside, constant outside',
          hint1: 'Charges reside only on the surface of a conductor.',
          hint2: 'Inside: E = 0 (Gauss\'s law, no enclosed charge).',
          hint3: 'At surface: E = kQ/R² (maximum); outside: E = kQ/r² (decreasing).',
          answer: 'B', level: 2,
        },
        {
          question: '[PYQ JEE Adv.] Electric potential at the centre of a square of side 2a with charge +q at each corner:',
          optA: 'kq/a', optB: '2kq/a', optC: '2√2 kq/a', optD: '4kq/a',
          hint1: 'Potential is scalar — add contributions from all 4 corners.',
          hint2: 'Distance from centre to each corner = a√2 (for a square of side 2a).',
          hint3: 'V = 4 × kq/(a√2) = 4kq/(a√2) = 2√2 kq/a.',
          answer: 'C', level: 3,
        },
      ],

      'Modern Physics': [
        {
          question: 'Work function of a metal is 2 eV. Its threshold frequency (h = 6.63×10⁻³⁴, e = 1.6×10⁻¹⁹):',
          optA: '4.83×10¹⁴ Hz', optB: '2×10¹⁴ Hz', optC: '6×10¹⁴ Hz', optD: '8×10¹⁴ Hz',
          hint1: 'At threshold: hν₀ = φ (work function).',
          hint2: 'ν₀ = φ/h = (2 × 1.6×10⁻¹⁹)/(6.63×10⁻³⁴).',
          hint3: 'ν₀ ≈ 4.83×10¹⁴ Hz.',
          answer: 'A', level: 1,
        },
        {
          question: 'In Bohr\'s model of hydrogen, radius of the 2nd orbit (a₀ = 0.529 Å):',
          optA: '0.529 Å', optB: '1.06 Å', optC: '2.12 Å', optD: '4.77 Å',
          hint1: 'Bohr radius for nth orbit: rₙ = n²a₀.',
          hint2: 'For n = 2: r₂ = 4 × 0.529 Å.',
          hint3: 'r₂ = 2.116 Å ≈ 2.12 Å.',
          answer: 'C', level: 1,
        },
        {
          question: 'Half-life of a radioactive element = 30 days. Fraction remaining after 90 days:',
          optA: '1/4', optB: '1/8', optC: '1/16', optD: '1/32',
          hint1: 'After n half-lives, fraction remaining = (1/2)ⁿ.',
          hint2: 'n = 90/30 = 3 half-lives.',
          hint3: 'Fraction = (1/2)³ = 1/8.',
          answer: 'B', level: 2,
        },
        {
          question: '[PYQ] X-rays of wavelength 2 Å are Compton-scattered at 90°. Wavelength of scattered ray (Δλ = h/mₑc = 0.0243 Å):',
          optA: '2.012 Å', optB: '2.024 Å', optC: '1.976 Å', optD: '2.048 Å',
          hint1: 'Compton formula: Δλ = (h/mₑc)(1 − cosθ).',
          hint2: 'At θ = 90°: Δλ = h/mₑc = 0.0243 Å.',
          hint3: 'λ\' = 2 + 0.0243 ≈ 2.024 Å.',
          answer: 'B', level: 2,
        },
        {
          question: '[PYQ JEE] Hydrogen atom transition n=4 → n=2. Wavelength of emitted photon (R_H = 1.097×10⁷ m⁻¹):',
          optA: '121.6 nm', optB: '486 nm', optC: '656 nm', optD: '1875 nm',
          hint1: 'Identify the series: lower level n=2 → Balmer series.',
          hint2: '1/λ = R_H(1/n₁² − 1/n₂²) = R_H(1/4 − 1/16) = 3R_H/16.',
          hint3: 'λ = 16/(3×1.097×10⁷) ≈ 486 nm — the Hβ line.',
          answer: 'B', level: 3,
        },
      ],

    },
  },

  // ══════════════════════════════════════════════════════════
  // CHEMISTRY
  // ══════════════════════════════════════════════════════════
  Chemistry: {
    icon: '⚗️',
    topics: {

      'Atomic Structure': [
        {
          question: 'Total number of nodes in the 3p orbital:',
          optA: '1', optB: '2', optC: '3', optD: '4',
          hint1: 'Total nodes = n − 1.',
          hint2: 'Radial nodes = n − l − 1; angular nodes = l.',
          hint3: 'For 3p (n=3, l=1): radial=1, angular=1 → total = 2.',
          answer: 'B', level: 1,
        },
        {
          question: 'Which set of quantum numbers is NOT allowed: (n=3, l=3, m=0)?',
          optA: 'Valid set', optB: 'Not allowed — l cannot equal n', optC: 'Not allowed — m is out of range', optD: 'Valid for a d-orbital',
          hint1: 'For a given n, l can be 0, 1, 2, ..., (n−1) only.',
          hint2: 'For n = 3, maximum allowed l = 2.',
          hint3: 'l = 3 when n = 3 is not allowed → invalid.',
          answer: 'B', level: 1,
        },
        {
          question: 'Energy of electron in He⁺ (Z=2) for n=2 (using E = −13.6 Z²/n² eV):',
          optA: '−3.4 eV', optB: '−13.6 eV', optC: '−27.2 eV', optD: '−54.4 eV',
          hint1: 'E_n = −13.6 Z²/n² eV.',
          hint2: 'Z = 2, n = 2.',
          hint3: 'E = −13.6 × 4/4 = −13.6 eV.',
          answer: 'B', level: 2,
        },
        {
          question: 'The correct electron configuration of Cu (Z = 29):',
          optA: '[Ar] 3d⁹ 4s²', optB: '[Ar] 3d¹⁰ 4s¹', optC: '[Ar] 3d⁸ 4s²', optD: '[Ar] 3d¹⁰ 4s²',
          hint1: 'Expected [Ar] 3d⁹ 4s², but there is an exception.',
          hint2: 'Completely filled d-orbitals (3d¹⁰) are extra stable.',
          hint3: 'One electron shifts 4s→3d: [Ar] 3d¹⁰ 4s¹.',
          answer: 'B', level: 2,
        },
        {
          question: '[PYQ JEE Adv.] Ratio of de Broglie wavelength of electron to proton (λ_e/λ_p) accelerated through the same potential difference V:',
          optA: '1/43', optB: '43', optC: '1836', optD: '√1836',
          hint1: 'λ = h/√(2mqV); for same charge and same V, λ ∝ 1/√m.',
          hint2: 'λ_e/λ_p = √(m_p/m_e).',
          hint3: 'm_p/m_e ≈ 1836, so ratio ≈ √1836 ≈ 43.',
          answer: 'B', level: 3,
        },
      ],

      'Chemical Bonding': [
        {
          question: 'Shape of SF₆ molecule:',
          optA: 'Trigonal bipyramidal', optB: 'Octahedral', optC: 'Square planar', optD: 'Tetrahedral',
          hint1: 'Count bond pairs and lone pairs on S.',
          hint2: 'SF₆: S forms 6 bonds, no lone pairs.',
          hint3: '6 bond pairs, 0 lone pairs → octahedral.',
          answer: 'B', level: 1,
        },
        {
          question: 'Which molecule has the highest bond order among N₂, O₂, F₂, Ne₂?',
          optA: 'F₂', optB: 'O₂', optC: 'N₂', optD: 'Ne₂',
          hint1: 'Bond order = (bonding e⁻ − antibonding e⁻)/2.',
          hint2: 'N≡N (triple), O=O (double), F−F (single), Ne₂ (zero).',
          hint3: 'N₂ has bond order 3 — the highest.',
          answer: 'C', level: 1,
        },
        {
          question: 'Number of lone pairs on Xe in XeF₂:',
          optA: '2', optB: '3', optC: '4', optD: '1',
          hint1: 'Xe has 8 valence electrons; 2 are used in bonds with F.',
          hint2: 'Remaining 6 electrons = 3 lone pairs.',
          hint3: '2 bond pairs + 3 lone pairs → linear shape (VSEPR).',
          answer: 'B', level: 2,
        },
        {
          question: 'Among ethane, ethene, ethyne, benzene — which has the shortest C–C bond?',
          optA: 'Ethane', optB: 'Ethene', optC: 'Ethyne', optD: 'Benzene',
          hint1: 'Bond length decreases as bond order increases.',
          hint2: 'Bond orders: C−C=1, C=C=2, C≡C=3.',
          hint3: 'Ethyne (C≡C) has bond order 3 → shortest distance ≈ 1.20 Å.',
          answer: 'C', level: 2,
        },
        {
          question: '[PYQ JEE Adv.] Formal charge on N in NO₃⁻ (one resonance structure with 1 double bond):',
          optA: '0', optB: '+1', optC: '−1', optD: '+2',
          hint1: 'FC = Valence e⁻ − Lone pair e⁻ − ½(Bond e⁻).',
          hint2: 'N in NO₃⁻ has 4 bonds (8 bonding e⁻) and 0 lone pairs.',
          hint3: 'FC(N) = 5 − 0 − ½(8) = 5 − 4 = +1.',
          answer: 'B', level: 3,
        },
      ],

      'Thermodynamics': [
        {
          question: 'For an ideal gas undergoing isothermal process, which is true?',
          optA: 'ΔU = 0, Q = 0', optB: 'ΔU = 0, Q = W', optC: 'ΔU = W, Q = 0', optD: 'ΔU = Q = W',
          hint1: 'Isothermal → temperature constant.',
          hint2: 'For ideal gas, internal energy depends only on T: ΔT = 0 → ΔU = 0.',
          hint3: 'First law: ΔU = Q − W → Q = W when ΔU = 0.',
          answer: 'B', level: 1,
        },
        {
          question: 'Standard enthalpy of combustion of CH₄ = −890 kJ/mol. Heat released by burning 8 g (M = 16 g/mol):',
          optA: '890 kJ', optB: '445 kJ', optC: '222.5 kJ', optD: '1780 kJ',
          hint1: 'Find moles of CH₄ first.',
          hint2: 'moles = 8/16 = 0.5 mol.',
          hint3: 'Heat = 0.5 × 890 = 445 kJ.',
          answer: 'B', level: 1,
        },
        {
          question: 'ΔHf(H₂O, l) = −286 kJ/mol; ΔHf(H₂O, g) = −242 kJ/mol. Enthalpy of vaporisation of water:',
          optA: '44 kJ/mol', optB: '528 kJ/mol', optC: '−44 kJ/mol', optD: '242 kJ/mol',
          hint1: 'Hess\'s law: ΔH_vap = ΔHf(H₂O, g) − ΔHf(H₂O, l).',
          hint2: '= −242 − (−286).',
          hint3: '= +44 kJ/mol (endothermic — vaporisation requires energy).',
          answer: 'A', level: 2,
        },
        {
          question: 'For spontaneity at constant T and P, the necessary and sufficient condition is:',
          optA: 'ΔH < 0', optB: 'ΔS > 0', optC: 'ΔG < 0', optD: 'ΔU < 0',
          hint1: 'Neither ΔH < 0 nor ΔS > 0 alone guarantees spontaneity.',
          hint2: 'ΔG = ΔH − TΔS combines both effects.',
          hint3: 'Spontaneous process at constant T, P requires ΔG < 0.',
          answer: 'C', level: 2,
        },
        {
          question: '[PYQ JEE Adv.] 1 mol ideal gas (γ = 5/3) expands adiabatically from P₁=10 atm, T₁=600 K to P₂=1 atm. Final temperature:',
          optA: '60 K', optB: '150 K', optC: '239 K', optD: '300 K',
          hint1: 'Use adiabatic relation: T₂/T₁ = (P₂/P₁)^((γ−1)/γ).',
          hint2: '(γ−1)/γ = (2/3)/(5/3) = 2/5; T₂ = 600 × (1/10)^(2/5).',
          hint3: 'T₂ = 600 × 10^(−0.4) = 600/2.512 ≈ 239 K.',
          answer: 'C', level: 3,
        },
      ],

      'Electrochemistry': [
        {
          question: 'How many moles of H₂ are produced at the cathode by passage of 2 Faradays through H₂O?',
          optA: '0.5 mol', optB: '1 mol', optC: '2 mol', optD: '4 mol',
          hint1: 'Cathode reaction: 2H⁺ + 2e⁻ → H₂ (requires 2 F per mole).',
          hint2: '2 Faradays = 2 moles of electrons.',
          hint3: '2 mol e⁻ → 1 mol H₂.',
          answer: 'B', level: 1,
        },
        {
          question: 'E°(Zn²⁺/Zn) = −0.76 V, E°(Cu²⁺/Cu) = +0.34 V. E°cell for Zn|Zn²⁺||Cu²⁺|Cu:',
          optA: '0.42 V', optB: '1.10 V', optC: '−1.10 V', optD: '0.76 V',
          hint1: 'E°cell = E°cathode − E°anode.',
          hint2: 'Cathode: Cu²⁺/Cu = +0.34 V; Anode: Zn/Zn²⁺, so E°anode = −0.76 V.',
          hint3: 'E°cell = 0.34 − (−0.76) = 1.10 V.',
          answer: 'B', level: 1,
        },
        {
          question: 'Kohlrausch\'s law (Λm = Λ°m − K√C) applies to:',
          optA: 'Weak electrolytes at high dilution', optB: 'Strong electrolytes at low concentration', optC: 'Non-electrolytes', optD: 'All electrolytes equally',
          hint1: 'This linear relation between Λm and √C must hold experimentally.',
          hint2: 'Weak electrolytes show a sharp non-linear increase at high dilution.',
          hint3: 'The linear law holds only for strong electrolytes where dissociation is complete.',
          answer: 'B', level: 2,
        },
        {
          question: 'Electrolysis of CuSO₄ with Cu electrodes deposits 0.635 g Cu (M = 63.5 g/mol, F = 96500). Charge passed:',
          optA: '965 C', optB: '1930 C', optC: '3860 C', optD: '96500 C',
          hint1: 'Cu²⁺ + 2e⁻ → Cu (n-factor = 2).',
          hint2: 'moles of Cu = 0.635/63.5 = 0.01 mol; moles of e⁻ = 0.01 × 2 = 0.02.',
          hint3: 'Q = 0.02 × 96500 = 1930 C.',
          answer: 'B', level: 2,
        },
        {
          question: '[PYQ JEE Adv.] For Mg|Mg²⁺||Cu²⁺|Cu with E°cell = 2.71 V: ΔG° and log K at 298 K (F = 96500, 0.0591 V/decade):',
          optA: 'ΔG° ≈ −523 kJ/mol, log K ≈ 91.7', optB: 'ΔG° ≈ −261 kJ/mol, log K ≈ 45', optC: 'ΔG° ≈ +523 kJ/mol, log K ≈ −91.7', optD: 'ΔG° ≈ −523 kJ/mol, log K ≈ 45',
          hint1: 'ΔG° = −nFE°cell, n = 2.',
          hint2: 'ΔG° = −2 × 96500 × 2.71 = −523,430 J ≈ −523.4 kJ/mol.',
          hint3: 'log K = nE°/0.0591 = 2 × 2.71/0.0591 ≈ 91.7.',
          answer: 'A', level: 3,
        },
      ],

      'Organic Chemistry': [
        {
          question: 'In 2-methylbutane, the count of primary (1°), secondary (2°), and tertiary (3°) carbons:',
          optA: '1° = 3, 2° = 1, 3° = 1', optB: '1° = 2, 2° = 2, 3° = 1', optC: '1° = 2, 2° = 1, 3° = 2', optD: '1° = 3, 2° = 2, 3° = 0',
          hint1: 'Primary C (1°): bonded to 1 other C; 2°: 2 C; 3°: 3 C.',
          hint2: 'Structure: CH₃−CH(CH₃)−CH₂−CH₃.',
          hint3: '3 primary C (the three CH₃ groups), 1 secondary (CH₂), 1 tertiary (CH).',
          answer: 'A', level: 1,
        },
        {
          question: 'Correct IUPAC name for CH₃−CH=CH−CH₃:',
          optA: '2-butene', optB: 'But-2-ene', optC: '2-methylpropene', optD: 'But-1-ene',
          hint1: 'Identify the parent chain and position of double bond.',
          hint2: '4-carbon chain with double bond starting at C2.',
          hint3: 'Modern IUPAC: but-2-ene (locant before suffix).',
          answer: 'B', level: 1,
        },
        {
          question: 'Major product of SN1 reaction of (CH₃)₃CBr with H₂O:',
          optA: '2-methylpropene', optB: '(CH₃)₃COH', optC: '(CH₃)₂C=CH₂', optD: '(CH₃)₃CCl',
          hint1: 'Tertiary halide → SN1 (stable 3° carbocation forms readily).',
          hint2: 'Step 1: (CH₃)₃CBr → (CH₃)₃C⁺ + Br⁻.',
          hint3: 'H₂O attacks carbocation → (CH₃)₃C-OH₂⁺ → loses H⁺ → (CH₃)₃COH.',
          answer: 'B', level: 2,
        },
        {
          question: 'HBr adds to propene (CH₃CH=CH₂) by Markovnikov\'s rule. Major product:',
          optA: '1-bromopropane', optB: '2-bromopropane', optC: 'Propane', optD: 'Allyl bromide',
          hint1: 'Markovnikov: H⁺ adds to the carbon bearing more H atoms.',
          hint2: 'CH₂ end (2 H) gets the H; more stable 2° carbocation forms at C2.',
          hint3: 'Br⁻ attacks C2 → 2-bromopropane (CH₃CHBrCH₃).',
          answer: 'B', level: 2,
        },
        {
          question: '[PYQ JEE Adv.] Nitration of benzene: the electrophile and mechanism type are:',
          optA: 'NO₂⁺, nucleophilic substitution', optB: 'NO₂⁻, electrophilic addition', optC: 'NO₂⁺, electrophilic aromatic substitution', optD: 'HNO₃, free radical',
          hint1: 'HNO₃ + H₂SO₄ → NO₂⁺ (nitronium ion) + HSO₄⁻ + H₂O.',
          hint2: 'Benzene\'s π-cloud attacks the electrophile NO₂⁺.',
          hint3: 'Wheland intermediate forms, then H⁺ is lost to restore aromaticity — EAS.',
          answer: 'C', level: 3,
        },
      ],

    },
  },

  // ══════════════════════════════════════════════════════════
  // MATHS
  // ══════════════════════════════════════════════════════════
  Maths: {
    icon: '∑',
    topics: {

      'Limits & Continuity': [
        {
          question: 'lim(x→0) sin(3x) / sin(2x) = ?',
          optA: '1', optB: '3/2', optC: '2/3', optD: '0',
          hint1: 'Use standard limit: lim(x→0) sinx/x = 1.',
          hint2: 'Write as (sin3x/3x) × (3x/2x) × (2x/sin2x).',
          hint3: '= 1 × (3/2) × 1 = 3/2.',
          answer: 'B', level: 1,
        },
        {
          question: 'f(x) = |x|/x for x ≠ 0. Is f continuous at x = 0?',
          optA: 'Yes, defining f(0) = 0 makes it continuous', optB: 'No, left and right limits differ', optC: 'Yes, if we define f(0) = 1', optD: 'Continuous everywhere',
          hint1: 'Check left-hand and right-hand limits at x = 0.',
          hint2: 'For x > 0: |x|/x = 1; for x < 0: |x|/x = −1.',
          hint3: 'LHL = −1 ≠ RHL = 1 → f is discontinuous at x = 0.',
          answer: 'B', level: 1,
        },
        {
          question: 'lim(x→0) (1 − cos x) / x² = ?',
          optA: '0', optB: '1', optC: '1/2', optD: '2',
          hint1: 'Use Taylor expansion: cos x ≈ 1 − x²/2 + ...',
          hint2: '(1 − cos x)/x² ≈ (x²/2)/x² = 1/2.',
          hint3: 'Or apply L\'Hôpital twice: → sinx/2x → cosx/2 → 1/2.',
          answer: 'C', level: 2,
        },
        {
          question: 'f(x) = (x² − 9)/(x − 3) for x ≠ 3, and f(3) = k for continuity. Then k = ?',
          optA: '3', optB: '6', optC: '9', optD: '0',
          hint1: 'For continuity, f(3) must equal lim(x→3) f(x).',
          hint2: 'Factor: (x²−9)/(x−3) = (x+3)(x−3)/(x−3) = x+3.',
          hint3: 'lim(x→3)(x+3) = 6, so k = 6.',
          answer: 'B', level: 2,
        },
        {
          question: 'lim(x→∞) (1 + 2/x)^x = ?',
          optA: 'e', optB: 'e²', optC: '2', optD: '1',
          hint1: 'Recognise the standard form: lim(1 + t)^(1/t) = e as t → 0.',
          hint2: 'Write (1 + 2/x)^x = [(1 + 2/x)^(x/2)]².',
          hint3: 'As x → ∞, (1 + 2/x)^(x/2) → e, so limit = e².',
          answer: 'B', level: 3,
        },
      ],

      'Integration': [
        {
          question: '∫ sin²x dx = ?',
          optA: '−cos²x + C', optB: 'x/2 − sin(2x)/4 + C', optC: '−sin x cos x + C', optD: 'cos²x/2 + C',
          hint1: 'Use identity: sin²x = (1 − cos2x)/2.',
          hint2: '∫(1 − cos2x)/2 dx = x/2 − sin2x/4 + C.',
          hint3: '= x/2 − sin(2x)/4 + C.',
          answer: 'B', level: 1,
        },
        {
          question: '∫₀¹ xeˣ dx = ?',
          optA: 'e', optB: '1', optC: 'e − 1', optD: '2e − 1',
          hint1: 'Use integration by parts: ∫u dv = uv − ∫v du.',
          hint2: 'Let u = x, dv = eˣ dx → du = dx, v = eˣ.',
          hint3: '[xeˣ − eˣ]₀¹ = (e − e) − (0 − 1) = 1.',
          answer: 'B', level: 1,
        },
        {
          question: '∫ dx / (x² + 2x + 5) = ?',
          optA: 'arctan(x+1) + C', optB: '½ arctan((x+1)/2) + C', optC: 'ln(x²+2x+5) + C', optD: 'arctan(x+2) + C',
          hint1: 'Complete the square in the denominator.',
          hint2: 'x² + 2x + 5 = (x+1)² + 4 = (x+1)² + 2².',
          hint3: 'Use ∫dx/(x²+a²) = (1/a)arctan(x/a): answer = ½arctan((x+1)/2) + C.',
          answer: 'B', level: 2,
        },
        {
          question: 'Actual area enclosed between y = x² − 4 and the x-axis from x = 0 to x = 2:',
          optA: '8/3', optB: '16/3', optC: '4', optD: '8',
          hint1: 'Check sign: x² − 4 < 0 on (0, 2) since x² < 4 there.',
          hint2: 'Actual area = |∫₀²(x² − 4) dx|.',
          hint3: '|[x³/3 − 4x]₀²| = |8/3 − 8| = 16/3.',
          answer: 'B', level: 2,
        },
        {
          question: '[PYQ JEE Adv.] ∫₀^(π/2) log(sin x) dx = ?',
          optA: '0', optB: 'π/2', optC: '−(π/2) ln 2', optD: '(π/2) ln 2',
          hint1: 'Use King\'s property: I = ∫₀^(π/2) log(cos x) dx = same value.',
          hint2: '2I = ∫₀^(π/2) log(sin x cos x) dx = ∫₀^(π/2) [log(sin 2x) − log 2] dx.',
          hint3: '2I = I − (π/2) log 2 → I = −(π/2) ln 2.',
          answer: 'C', level: 3,
        },
      ],

      'Matrices & Determinants': [
        {
          question: 'If A = [[2, 3], [1, 4]], then det(A) = ?',
          optA: '5', optB: '11', optC: '8', optD: '3',
          hint1: 'For 2×2 matrix [[a,b],[c,d]], det = ad − bc.',
          hint2: 'det = 2×4 − 3×1.',
          hint3: '= 8 − 3 = 5.',
          answer: 'A', level: 1,
        },
        {
          question: 'A is a 3×3 matrix with det(A) = 4. Then det(2A) = ?',
          optA: '8', optB: '16', optC: '32', optD: '64',
          hint1: 'Property: det(kA) = kⁿ × det(A) for an n×n matrix.',
          hint2: 'n = 3, k = 2: det(2A) = 2³ × det(A).',
          hint3: '= 8 × 4 = 32.',
          answer: 'C', level: 1,
        },
        {
          question: 'If A = [[1,2],[3,4]], then A⁻¹ = ?',
          optA: '[[−2, 1], [3/2, −½]]', optB: '[[4, −2], [−3, 1]]', optC: '[[½, 1], [3/2, 2]]', optD: 'Does not exist',
          hint1: 'A⁻¹ = (1/det(A)) × adj(A).',
          hint2: 'det(A) = 4 − 6 = −2; adj(A) = [[4, −2], [−3, 1]].',
          hint3: 'A⁻¹ = (−½)[[4,−2],[−3,1]] = [[−2,1],[3/2,−½]].',
          answer: 'A', level: 2,
        },
        {
          question: 'System: x + y = 3, 2x + 2y = 7. Nature of solution:',
          optA: 'Unique solution', optB: 'Infinitely many solutions', optC: 'No solution', optD: 'Two solutions',
          hint1: 'Compute determinant D of the coefficient matrix.',
          hint2: 'D = |1 1; 2 2| = 2−2 = 0; then check D₁ = |3 1; 7 2| = 6−7 = −1.',
          hint3: 'D = 0 but D₁ ≠ 0 → inconsistent (no solution).',
          answer: 'C', level: 2,
        },
        {
          question: '[PYQ JEE Adv.] If A = [[0,1],[1,0]], then A¹⁰⁰ = ?',
          optA: '[[0,1],[1,0]]', optB: '[[1,0],[0,1]]', optC: '[[0,100],[100,0]]', optD: '[[100,0],[0,100]]',
          hint1: 'Compute A² first.',
          hint2: 'A² = [[0,1],[1,0]] × [[0,1],[1,0]] = [[1,0],[0,1]] = I.',
          hint3: 'A² = I → A^(2k) = I; 100 = 2×50, so A¹⁰⁰ = I.',
          answer: 'B', level: 3,
        },
      ],

      'Complex Numbers': [
        {
          question: '|3 + 4i| = ?',
          optA: '3', optB: '4', optC: '5', optD: '7',
          hint1: '|a + bi| = √(a² + b²).',
          hint2: '|3 + 4i| = √(9 + 16).',
          hint3: '= √25 = 5.',
          answer: 'C', level: 1,
        },
        {
          question: 'Argument of the complex number −1 + i:',
          optA: 'π/4', optB: '3π/4', optC: '−π/4', optD: 'π',
          hint1: 'Use arg(a + bi) adjusted for the correct quadrant.',
          hint2: '−1 + i is in the 2nd quadrant (a < 0, b > 0).',
          hint3: 'arg = π − arctan(1/1) = π − π/4 = 3π/4.',
          answer: 'B', level: 1,
        },
        {
          question: 'If ω is a complex cube root of unity, 1 + ω + ω² = ?',
          optA: '1', optB: '−1', optC: '0', optD: 'ω',
          hint1: 'The three cube roots of unity satisfy x³ = 1.',
          hint2: 'x³ − 1 = (x−1)(x²+x+1) = 0; since ω ≠ 1: ω² + ω + 1 = 0.',
          hint3: 'Therefore 1 + ω + ω² = 0.',
          answer: 'C', level: 2,
        },
        {
          question: '(1 + i)⁸ = ?',
          optA: '8', optB: '16', optC: '−16', optD: '4i',
          hint1: 'Compute (1+i)² first.',
          hint2: '(1+i)² = 2i; (1+i)⁴ = (2i)² = −4.',
          hint3: '(1+i)⁸ = (−4)² = 16.',
          answer: 'B', level: 2,
        },
        {
          question: '[PYQ JEE Adv.] z₁ = 2+3i, z₂ = 1−i. Express z₁/z₂ in a+bi form:',
          optA: '(−1 + 5i)/2', optB: '(1 + 5i)/2', optC: '(−1 − 5i)/2', optD: '(5 − i)/2',
          hint1: 'Multiply numerator and denominator by the conjugate of z₂.',
          hint2: '(2+3i)(1+i) / [(1−i)(1+i)] = (2+2i+3i−3) / 2.',
          hint3: '= (−1 + 5i)/2.',
          answer: 'A', level: 3,
        },
      ],

      'Probability': [
        {
          question: 'Two dice are rolled. P(sum = 7):',
          optA: '1/12', optB: '1/6', optC: '5/36', optD: '7/36',
          hint1: 'Total outcomes = 6 × 6 = 36.',
          hint2: 'Pairs summing to 7: (1,6),(2,5),(3,4),(4,3),(5,2),(6,1) — 6 pairs.',
          hint3: 'P = 6/36 = 1/6.',
          answer: 'B', level: 1,
        },
        {
          question: 'Bag has 5 red and 3 blue balls. P(drawing 2 red in a row, without replacement):',
          optA: '25/64', optB: '5/14', optC: '5/16', optD: '1/7',
          hint1: 'Use conditional probability (without replacement — dependent events).',
          hint2: 'P(1st red) = 5/8; P(2nd red | 1st red) = 4/7.',
          hint3: 'P = 5/8 × 4/7 = 20/56 = 5/14.',
          answer: 'B', level: 1,
        },
        {
          question: 'P(A) = 0.4, P(B) = 0.3, P(A∩B) = 0.1. P(A∪B):',
          optA: '0.5', optB: '0.6', optC: '0.7', optD: '1.2',
          hint1: 'Use addition rule: P(A∪B) = P(A) + P(B) − P(A∩B).',
          hint2: '= 0.4 + 0.3 − 0.1.',
          hint3: '= 0.6.',
          answer: 'B', level: 2,
        },
        {
          question: 'Binomial distribution, n = 6, p = 1/3. P(X = 2):',
          optA: '15/243', optB: '80/243', optC: '60/243', optD: '20/81',
          hint1: 'P(X=k) = C(n,k) × pᵏ × (1−p)^(n−k).',
          hint2: 'C(6,2) = 15; (1/3)² = 1/9; (2/3)⁴ = 16/81.',
          hint3: 'P = 15 × (1/9) × (16/81) = 240/729 = 80/243.',
          answer: 'B', level: 2,
        },
        {
          question: '[PYQ JEE Adv. — Bayes] Box A: 3 red, 2 white. Box B: 2 red, 3 white. One box chosen randomly; one ball drawn — it is red. P(Box A was chosen):',
          optA: '1/2', optB: '3/5', optC: '2/5', optD: '3/10',
          hint1: 'Use Bayes\' theorem: P(A|Red) = P(A)P(R|A) / P(R).',
          hint2: 'P(R) = ½×(3/5) + ½×(2/5) = 1/2.',
          hint3: 'P(A|Red) = (½ × 3/5) / (1/2) = 3/5.',
          answer: 'B', level: 3,
        },
      ],

    },
  },

};