/* ============================================================
   data.js  —  Subject → Topic → Question Bank
   10 questions per topic (levels 1–3, JEE Mains / Advanced standard)
   ============================================================ */

const QUESTION_BANK = {

  // ══════════════════════════════════════════════════════════
  // PHYSICS
  // ══════════════════════════════════════════════════════════
  Physics: {
    icon: '⚡',
    topics: {

      'Kinematics': [
        {
          question: 'A ball is thrown horizontally at 20 m/s from a height of 80 m. Its horizontal range is (g = 10 m/s²):',
          optA: '40 m', optB: '60 m', optC: '80 m', optD: '100 m',
          hint1: 'First find time to fall using h = ½gt².',
          hint2: 't = √(2×80/10) = 4 s.',
          hint3: 'Range = horizontal speed × time = 20 × 4 = 80 m.',
          answer: 'C', level: 1,
        },
        {
          question: 'A body starts from rest with uniform acceleration 4 m/s². Distance covered in the 5th second is:',
          optA: '10 m', optB: '14 m', optC: '16 m', optD: '18 m',
          hint1: 'Use the formula for distance in nth second: sₙ = u + a(n − ½).',
          hint2: 'u = 0, a = 4, n = 5.',
          hint3: 's₅ = 0 + 4 × 4.5 = 18 m.',
          answer: 'D', level: 1,
        },
        {
          question: 'Train A moves east at 60 km/h; Train B moves west at 90 km/h. Speed of B relative to A:',
          optA: '30 km/h', optB: '90 km/h', optC: '150 km/h', optD: '60 km/h',
          hint1: 'Opposite directions → relative speeds add.',
          hint2: 'v_rel = v_B + v_A (magnitudes for opposite directions).',
          hint3: '60 + 90 = 150 km/h.',
          answer: 'C', level: 1,
        },
        {
          question: 'A projectile is launched at 45°. If maximum height is H, the horizontal range R equals:',
          optA: 'H', optB: '2H', optC: '3H', optD: '4H',
          hint1: 'Express both H and R in terms of initial speed u and g.',
          hint2: 'H = u²sin²45°/2g = u²/4g; R = u²sin90°/g = u²/g.',
          hint3: 'R/H = 4, so R = 4H.',
          answer: 'D', level: 2,
        },
        {
          question: 'A v–t graph: velocity increases linearly from 0 to 20 m/s over 5 s, remains constant for 3 s, then decreases to 0 in 2 s. Total distance covered:',
          optA: '110 m', optB: '120 m', optC: '130 m', optD: '140 m',
          hint1: 'Distance = area under v–t graph.',
          hint2: 'Three regions: triangle (0–5 s), rectangle (5–8 s), triangle (8–10 s).',
          hint3: '½×5×20 + 20×3 + ½×2×20 = 50 + 60 + 20 = 130 m.',
          answer: 'C', level: 3,
        },
        {
          question: 'A car moving at 72 km/h applies brakes and stops in 10 s. The retardation is:',
          optA: '1 m/s²', optB: '2 m/s²', optC: '4 m/s²', optD: '7.2 m/s²',
          hint1: 'Convert 72 km/h to m/s: 72 × 5/18 = 20 m/s.',
          hint2: 'Use v = u + at → 0 = 20 + a×10.',
          hint3: 'a = −2 m/s², so retardation = 2 m/s².',
          answer: 'B', level: 1,
        },
        {
          question: 'A particle has position x = 5t + 3t² − t³. When is the acceleration zero?',
          optA: 't = 0 s', optB: 't = 0.5 s', optC: 't = 1 s', optD: 't = 2 s',
          hint1: 'Acceleration = d²x/dt². First find velocity: v = 5 + 6t − 3t².',
          hint2: 'a = dv/dt = 6 − 6t.',
          hint3: '6 − 6t = 0 → t = 1 s.',
          answer: 'C', level: 2,
        },
        {
          question: 'A boat travels at 3 m/s relative to water, perpendicular to a river with current 4 m/s. Resultant speed of the boat:',
          optA: '1 m/s', optB: '3.5 m/s', optC: '5 m/s', optD: '7 m/s',
          hint1: 'Boat velocity and river current are perpendicular — use Pythagoras.',
          hint2: 'Resultant = √(v_boat² + v_river²).',
          hint3: '√(9 + 16) = √25 = 5 m/s.',
          answer: 'C', level: 1,
        },
        {
          question: 'A stone is tied to a 1 m string and revolves in a horizontal circle with time period 2 s. Its centripetal acceleration is:',
          optA: 'π²/2 m/s²', optB: 'π² m/s²', optC: '2π² m/s²', optD: '4π² m/s²',
          hint1: 'Centripetal acceleration a = 4π²R/T².',
          hint2: 'R = 1 m, T = 2 s.',
          hint3: 'a = 4π² × 1 / 4 = π² m/s².',
          answer: 'B', level: 2,
        },
        {
          question: '[PYQ JEE Adv.] A particle\'s position vector is r = (2t²î + 3tĵ) m. The magnitude of its acceleration at t = 2 s is:',
          optA: '2 m/s²', optB: '4 m/s²', optC: '√13 m/s²', optD: '6 m/s²',
          hint1: 'Velocity v = dr/dt = 4tî + 3ĵ.',
          hint2: 'Acceleration a = dv/dt = 4î (constant vector).',
          hint3: '|a| = 4 m/s² (independent of time).',
          answer: 'B', level: 3,
        },
      ],

      'Laws of Motion': [
        {
          question: 'An Atwood machine has m₁ = 3 kg and m₂ = 5 kg. Acceleration of the system (g = 10 m/s²):',
          optA: '1.25 m/s²', optB: '2.5 m/s²', optC: '5 m/s²', optD: '10 m/s²',
          hint1: 'Net force = (m₂ − m₁)g; total mass = m₁ + m₂.',
          hint2: 'a = (m₂ − m₁)g / (m₁ + m₂).',
          hint3: 'a = (2 × 10)/8 = 2.5 m/s².',
          answer: 'B', level: 1,
        },
        {
          question: 'A lift accelerates upward at 2 m/s². Apparent weight of a 60 kg passenger (g = 10 m/s²):',
          optA: '480 N', optB: '600 N', optC: '720 N', optD: '840 N',
          hint1: 'For upward acceleration: apparent weight = m(g + a).',
          hint2: 'W = 60 × (10 + 2).',
          hint3: 'W = 60 × 12 = 720 N.',
          answer: 'C', level: 1,
        },
        {
          question: 'A block (m = 2 kg) is pressed against a wall by horizontal force F = 60 N (μs = 0.4, g = 10). The friction force on the block is:',
          optA: '20 N upward', optB: '24 N upward', optC: 'Block slides down', optD: '60 N',
          hint1: 'Normal force from wall = F = 60 N. Static friction acts upward to balance weight.',
          hint2: 'Max static friction = μs × N = 0.4 × 60 = 24 N; Weight = 2 × 10 = 20 N.',
          hint3: 'Max friction (24 N) > weight (20 N), so equilibrium. Actual friction = weight = 20 N.',
          answer: 'A', level: 2,
        },
        {
          question: 'A 4 kg block on a smooth table is connected via a string over a pulley to hanging masses m₂ = 2 kg and m₃ = 1 kg (hanging from m₂). Acceleration of system (g = 10):',
          optA: '30/7 m/s²', optB: '10/3 m/s²', optC: '5 m/s²', optD: '3 m/s²',
          hint1: 'Only hanging masses (m₂ + m₃) provide the driving force.',
          hint2: 'Net force = (m₂ + m₃)g = 30 N; total mass = 4 + 2 + 1 = 7 kg.',
          hint3: 'a = 30/7 ≈ 4.3 m/s².',
          answer: 'A', level: 2,
        },
        {
          question: 'A block (5 kg) on a rough incline (θ = 30°, μ = 0.4) — minimum force parallel to incline to push it UP (g = 10):',
          optA: '25 N', optB: '32 N', optC: '42.3 N', optD: '50 N',
          hint1: 'Force needed = mg sinθ + μmg cosθ (friction also opposes upward motion).',
          hint2: 'F = mg(sinθ + μcosθ) = 50(0.5 + 0.4 × 0.866).',
          hint3: 'F = 50 × 0.846 ≈ 42.3 N.',
          answer: 'C', level: 3,
        },
        {
          question: 'A man stands in a lift descending at constant velocity. His apparent weight is:',
          optA: 'Zero', optB: 'Less than mg', optC: 'Equal to mg', optD: 'Greater than mg',
          hint1: 'Constant velocity means acceleration = 0.',
          hint2: 'Net force = 0 → Normal force = mg.',
          hint3: 'Apparent weight equals true weight when a = 0.',
          answer: 'C', level: 1,
        },
        {
          question: 'A 0.5 kg ball moving at 4 m/s is hit back at 6 m/s. The impulse imparted to the ball is:',
          optA: '1 N·s', optB: '5 N·s', optC: '3 N·s', optD: '10 N·s',
          hint1: 'Impulse = change in momentum = m(v₂ − v₁).',
          hint2: 'Take initial direction as positive: v₁ = 4, v₂ = −6 m/s (reversed).',
          hint3: 'J = 0.5 × (−6 − 4) = 0.5 × (−10) = −5 N·s → magnitude = 5 N·s.',
          answer: 'B', level: 1,
        },
        {
          question: 'A block rests on the floor of a car accelerating forward at 3 m/s². Minimum μs so the block does not slide (g = 10):',
          optA: '0.1', optB: '0.2', optC: '0.3', optD: '0.5',
          hint1: 'In the car\'s frame, pseudo force ma acts backward on the block.',
          hint2: 'Friction must balance pseudo force: f = ma, and f ≤ μmg.',
          hint3: 'μmin = a/g = 3/10 = 0.3.',
          answer: 'C', level: 2,
        },
        {
          question: 'For a car moving on a banked road of angle θ without friction, the ideal speed is:',
          optA: '√(gR tanθ)', optB: '√(gR sinθ)', optC: '√(gR/tanθ)', optD: 'gR tanθ',
          hint1: 'On a banked road, horizontal component of normal force provides centripetal force.',
          hint2: 'N sinθ = mv²/R and N cosθ = mg → tan θ = v²/gR.',
          hint3: 'v = √(gR tanθ).',
          answer: 'A', level: 2,
        },
        {
          question: '[PYQ JEE Adv.] A ball on a string moves in a vertical circle of radius 1 m. Minimum speed at the top so the string stays taut (g = 10 m/s²):',
          optA: '√5 m/s', optB: '√10 m/s', optC: '√15 m/s', optD: '√20 m/s',
          hint1: 'At the top, tension T + mg provides centripetal force: T + mg = mv²/R.',
          hint2: 'For minimum speed, T = 0 → mg = mv²_min/R.',
          hint3: 'v_min = √(gR) = √(10 × 1) = √10 m/s.',
          answer: 'B', level: 3,
        },
      ],

      'Work, Energy & Power': [
        {
          question: 'A spring (k = 200 N/m) is compressed by 10 cm. Energy stored:',
          optA: '0.5 J', optB: '1 J', optC: '2 J', optD: '4 J',
          hint1: 'Elastic PE = ½kx².',
          hint2: 'x = 0.1 m, k = 200 N/m.',
          hint3: 'U = ½ × 200 × 0.01 = 1 J.',
          answer: 'B', level: 1,
        },
        {
          question: 'A 4 kg ball falls from 5 m and bounces to 3.2 m. Energy lost to heat (g = 10):',
          optA: '32 J', optB: '56 J', optC: '72 J', optD: '128 J',
          hint1: 'Energy lost = change in potential energy.',
          hint2: 'ΔE = mg(h₁ − h₂).',
          hint3: 'ΔE = 4 × 10 × (5 − 3.2) = 72 J.',
          answer: 'C', level: 1,
        },
        {
          question: 'A force F = (20 − 4x) N acts on a body. Work done from x = 0 to x = 4 m:',
          optA: '32 J', optB: '40 J', optC: '48 J', optD: '56 J',
          hint1: 'W = ∫F dx when force varies with position.',
          hint2: 'W = ∫₀⁴(20 − 4x) dx = [20x − 2x²]₀⁴.',
          hint3: '= (80 − 32) − 0 = 48 J.',
          answer: 'C', level: 2,
        },
        {
          question: 'A ball hits a wall at 10 m/s and bounces back at 8 m/s. Coefficient of restitution e:',
          optA: '0.6', optB: '0.75', optC: '0.8', optD: '0.9',
          hint1: 'e = speed of rebound / speed of approach (wall is stationary).',
          hint2: 'e = 8/10.',
          hint3: 'e = 0.8.',
          answer: 'C', level: 2,
        },
        {
          question: 'A particle (2 kg) moves under potential U = (x² − 4x) J. Its equilibrium position and nature:',
          optA: 'x = 2 m, stable', optB: 'x = 2 m, unstable', optC: 'x = 4 m, stable', optD: 'x = 0, neutral',
          hint1: 'At equilibrium: F = −dU/dx = 0.',
          hint2: 'dU/dx = 2x − 4 = 0 → x = 2 m.',
          hint3: 'd²U/dx² = 2 > 0 → potential minimum → stable equilibrium.',
          answer: 'A', level: 3,
        },
        {
          question: 'A 60 kg person climbs a 10 m staircase in 20 s (g = 10 m/s²). Power developed:',
          optA: '150 W', optB: '300 W', optC: '600 W', optD: '1200 W',
          hint1: 'Work done against gravity = mgh.',
          hint2: 'P = W/t = mgh/t.',
          hint3: 'P = 60 × 10 × 10 / 20 = 300 W.',
          answer: 'B', level: 1,
        },
        {
          question: 'Ball A (2 kg, 4 m/s) collides head-on elastically with ball B (2 kg, at rest). Velocities after collision:',
          optA: 'A: 4 m/s, B: 0', optB: 'A: 0, B: 4 m/s', optC: 'A: 2 m/s, B: 2 m/s', optD: 'A: −2 m/s, B: 2 m/s',
          hint1: 'In a perfectly elastic collision between equal masses, velocities exchange.',
          hint2: 'Momentum: 2×4 = 2×v₁ + 2×v₂; Energy: ½×2×16 = ½×2×v₁² + ½×2×v₂².',
          hint3: 'v₁ = 0, v₂ = 4 m/s.',
          answer: 'B', level: 1,
        },
        {
          question: 'A spring (k = 200 N/m, compressed 0.2 m) launches a 2 kg block on a smooth surface. Maximum speed of block:',
          optA: '1 m/s', optB: '2 m/s', optC: '3 m/s', optD: '4 m/s',
          hint1: 'All spring PE converts to kinetic energy at the natural length.',
          hint2: '½kx² = ½mv² → v² = kx²/m.',
          hint3: 'v² = 200 × 0.04 / 2 = 4 → v = 2 m/s.',
          answer: 'B', level: 2,
        },
        {
          question: 'A body of mass 1 kg is released from height 20 m on a curved slide. Speed at bottom (g = 10, ignore friction):',
          optA: '10 m/s', optB: '20 m/s', optC: '√200 m/s', optD: '40 m/s',
          hint1: 'Use conservation of energy: mgh = ½mv².',
          hint2: 'v² = 2gh = 2 × 10 × 20 = 400.',
          hint3: 'v = 20 m/s.',
          answer: 'B', level: 1,
        },
        {
          question: '[PYQ JEE Adv.] Two blocks 2 kg and 3 kg connected by a spring (k = 200 N/m) on a frictionless surface. The 2 kg block is given velocity 2 m/s toward the stationary 3 kg block. Maximum spring compression:',
          optA: '0.10 m', optB: '0.15 m', optC: '0.20 m', optD: '0.30 m',
          hint1: 'At maximum compression, both blocks have the same velocity v_cm.',
          hint2: 'v_cm = (2×2)/(2+3) = 0.8 m/s. Energy: ½×2×4 = ½×5×0.64 + ½×200×x².',
          hint3: '4 − 1.6 = 100x² → x² = 0.024 → x ≈ 0.155 ≈ 0.15 m.',
          answer: 'B', level: 3,
        },
      ],

      'Electrostatics': [
        {
          question: 'Two charges of +3 µC each are separated by 3 cm. Force between them (k = 9×10⁹):',
          optA: '30 N', optB: '60 N', optC: '90 N', optD: '120 N',
          hint1: 'Use Coulomb\'s law: F = kq₁q₂/r².',
          hint2: 'q₁ = q₂ = 3×10⁻⁶ C, r = 0.03 m.',
          hint3: 'F = 9×10⁹ × 9×10⁻¹² / (9×10⁻⁴) = 90 N.',
          answer: 'C', level: 1,
        },
        {
          question: 'An electron accelerated through 100 V gains kinetic energy of (e = 1.6×10⁻¹⁹ C):',
          optA: '1.6×10⁻¹⁹ J', optB: '1.6×10⁻¹⁷ J', optC: '1.6×10⁻²¹ J', optD: '100 J',
          hint1: 'Work done on a charge = |q| × ΔV.',
          hint2: 'KE gained = eV = 1.6×10⁻¹⁹ × 100.',
          hint3: 'KE = 1.6×10⁻¹⁷ J.',
          answer: 'B', level: 1,
        },
        {
          question: 'A parallel plate capacitor (area A, separation d) has a dielectric slab (thickness t, constant K) inserted. New capacitance:',
          optA: 'ε₀A / (d − t + t/K)', optB: 'Kε₀A / d', optC: 'ε₀A / d', optD: 'Kε₀A / (d − t)',
          hint1: 'The slab creates two gaps in series: air (d − t) and dielectric (t).',
          hint2: '1/C = (d − t)/(ε₀A) + t/(Kε₀A).',
          hint3: 'C = ε₀A / (d − t + t/K).',
          answer: 'A', level: 2,
        },
        {
          question: 'A spherical conductor of radius R carries charge Q. Which E vs r graph is correct?',
          optA: 'E increases linearly inside, then decreases as 1/r² outside',
          optB: 'E = 0 inside, maximum at surface, decreases as 1/r² outside',
          optC: 'E is uniform everywhere',
          optD: 'E increases as r² inside, constant outside',
          hint1: 'Charges reside only on the surface of a conductor.',
          hint2: 'Inside conductor in electrostatic equilibrium: E = 0 by Gauss\'s law.',
          hint3: 'At surface: E = kQ/R² (maximum); outside: E = kQ/r² (decreasing).',
          answer: 'B', level: 2,
        },
        {
          question: '[PYQ JEE Adv.] Electric potential at the centre of a square of side 2a with charge +q at each corner:',
          optA: 'kq/a', optB: '2kq/a', optC: '2√2 kq/a', optD: '4kq/a',
          hint1: 'Potential is scalar — add contributions from all 4 corners.',
          hint2: 'Distance from centre to each corner = √2 × a (for a square of side 2a).',
          hint3: 'V = 4 × kq/(a√2) = 2√2 kq/a.',
          answer: 'C', level: 3,
        },
        {
          question: 'Total electric flux through a closed surface enclosing charge Q (in vacuum):',
          optA: 'Q', optB: 'Q/ε₀', optC: 'ε₀Q', optD: 'kQ',
          hint1: 'This is Gauss\'s law.',
          hint2: 'Φ = ∮E·dA = Q_enclosed / ε₀.',
          hint3: 'Φ = Q/ε₀.',
          answer: 'B', level: 1,
        },
        {
          question: 'Two capacitors C₁ = 4 µF and C₂ = 6 µF are connected in series to a 100 V battery. Voltage across C₁:',
          optA: '40 V', optB: '60 V', optC: '50 V', optD: '67 V',
          hint1: 'In series, same charge Q on both. Q = C_eff × V.',
          hint2: 'C_eff = (4×6)/(4+6) = 2.4 µF; Q = 2.4 × 100 = 240 µC.',
          hint3: 'V₁ = Q/C₁ = 240/4 = 60 V.',
          answer: 'B', level: 2,
        },
        {
          question: 'Energy stored in a 10 µF capacitor charged to 200 V:',
          optA: '0.1 J', optB: '0.2 J', optC: '0.4 J', optD: '2 J',
          hint1: 'U = ½CV².',
          hint2: 'C = 10×10⁻⁶ F, V = 200 V.',
          hint3: 'U = ½ × 10⁻⁵ × 40000 = 0.2 J.',
          answer: 'B', level: 1,
        },
        {
          question: 'An electric dipole (dipole moment p) is placed in a uniform field E at angle 60° with E. Torque on dipole:',
          optA: 'pE/2', optB: 'pE√3/2', optC: 'pE', optD: '2pE',
          hint1: 'Torque τ = pE sinθ.',
          hint2: 'θ = 60°, sin 60° = √3/2.',
          hint3: 'τ = pE × √3/2.',
          answer: 'B', level: 2,
        },
        {
          question: '[PYQ JEE Adv.] A uniformly charged sphere of radius R has total charge Q. Electric field at distance r < R from the centre:',
          optA: 'kQ/r²', optB: 'kQr/R³', optC: 'kQ/R²', optD: '0',
          hint1: 'Apply Gauss\'s law with a spherical surface of radius r inside the sphere.',
          hint2: 'Charge enclosed = Q × (r³/R³) (volume ratio for uniform distribution).',
          hint3: 'E = kQ_enc/r² = kQr/R³.',
          answer: 'B', level: 3,
        },
      ],

      'Modern Physics': [
        {
          question: 'Work function of a metal is 2 eV. Its threshold frequency (h = 6.63×10⁻³⁴, e = 1.6×10⁻¹⁹):',
          optA: '4.83×10¹⁴ Hz', optB: '2×10¹⁴ Hz', optC: '6×10¹⁴ Hz', optD: '8×10¹⁴ Hz',
          hint1: 'At threshold: hν₀ = φ (work function).',
          hint2: 'ν₀ = φ/h = (2 × 1.6×10⁻¹⁹) / (6.63×10⁻³⁴).',
          hint3: 'ν₀ ≈ 4.83×10¹⁴ Hz.',
          answer: 'A', level: 1,
        },
        {
          question: 'In Bohr\'s model of hydrogen, radius of the 2nd orbit (a₀ = 0.529 Å):',
          optA: '0.529 Å', optB: '1.06 Å', optC: '2.12 Å', optD: '4.77 Å',
          hint1: 'Bohr radius for nth orbit: rₙ = n² a₀.',
          hint2: 'For n = 2: r₂ = 4 × 0.529 Å.',
          hint3: 'r₂ = 2.116 Å ≈ 2.12 Å.',
          answer: 'C', level: 1,
        },
        {
          question: 'Half-life of a radioactive element = 30 days. Fraction remaining after 90 days:',
          optA: '1/4', optB: '1/8', optC: '1/16', optD: '1/32',
          hint1: 'After n half-lives, fraction remaining = (1/2)ⁿ.',
          hint2: 'n = 90/30 = 3 half-lives.',
          hint3: 'Fraction = (1/2)³ = 1/8.',
          answer: 'B', level: 1,
        },
        {
          question: '[PYQ] X-rays of wavelength 2 Å are Compton-scattered at 90°. Wavelength of scattered ray (Δλ = h/mₑc = 0.0243 Å):',
          optA: '2.012 Å', optB: '2.024 Å', optC: '1.976 Å', optD: '2.048 Å',
          hint1: 'Compton formula: Δλ = (h/mₑc)(1 − cosθ).',
          hint2: 'At θ = 90°: Δλ = h/mₑc = 0.0243 Å.',
          hint3: 'λ\' = 2 + 0.0243 ≈ 2.024 Å.',
          answer: 'B', level: 2,
        },
        {
          question: '[PYQ JEE] Hydrogen atom transition n = 4 → n = 2. Wavelength of emitted photon (R_H = 1.097×10⁷ m⁻¹):',
          optA: '121.6 nm', optB: '486 nm', optC: '656 nm', optD: '1875 nm',
          hint1: 'Lower level n = 2 → Balmer series.',
          hint2: '1/λ = R_H(1/n₁² − 1/n₂²) = R_H(1/4 − 1/16) = 3R_H/16.',
          hint3: 'λ = 16/(3 × 1.097×10⁷) ≈ 486 nm — the Hβ line.',
          answer: 'B', level: 3,
        },
        {
          question: 'In β⁻ decay, the atomic number of the daughter nucleus compared to parent:',
          optA: 'Decreases by 1', optB: 'Increases by 1', optC: 'Unchanged', optD: 'Increases by 2',
          hint1: 'β⁻ decay: n → p + e⁻ + antineutrino.',
          hint2: 'A neutron converts to a proton inside the nucleus.',
          hint3: 'Proton count (Z) increases by 1; mass number (A) stays the same.',
          answer: 'B', level: 1,
        },
        {
          question: 'Energy equivalent of 1 atomic mass unit (1 amu) in MeV:',
          optA: '1.5 MeV', optB: '931.5 MeV', optC: '3.7 MeV', optD: '938 MeV',
          hint1: 'Use E = mc² with 1 amu = 1.66×10⁻²⁷ kg.',
          hint2: 'E = 1.66×10⁻²⁷ × (3×10⁸)² = 1.49×10⁻¹⁰ J.',
          hint3: 'Convert to MeV: 1.49×10⁻¹⁰ / (1.6×10⁻¹³) ≈ 931.5 MeV.',
          answer: 'B', level: 1,
        },
        {
          question: 'de Broglie wavelength of an electron accelerated through 150 V (m = 9.1×10⁻³¹ kg, e = 1.6×10⁻¹⁹ C, h = 6.63×10⁻³⁴):',
          optA: '0.1 Å', optB: '1 Å', optC: '10 Å', optD: '100 Å',
          hint1: 'λ = h / √(2meV).',
          hint2: 'KE = eV = 1.6×10⁻¹⁹ × 150 = 2.4×10⁻¹⁷ J.',
          hint3: 'λ = 6.63×10⁻³⁴ / √(2 × 9.1×10⁻³¹ × 2.4×10⁻¹⁷) ≈ 1 Å.',
          answer: 'B', level: 2,
        },
        {
          question: 'Energy of electron in hydrogen atom for n = 3:',
          optA: '−1.51 eV', optB: '−3.4 eV', optC: '−0.85 eV', optD: '−13.6 eV',
          hint1: 'Eₙ = −13.6 / n² eV for hydrogen.',
          hint2: 'n = 3.',
          hint3: 'E₃ = −13.6/9 ≈ −1.51 eV.',
          answer: 'A', level: 2,
        },
        {
          question: '[PYQ JEE Adv.] Photoelectric effect: stopping potentials are 1.85 V and 0.82 V for wavelengths 300 nm and 400 nm. Planck\'s constant from this data (e = 1.6×10⁻¹⁹ C, c = 3×10⁸ m/s):',
          optA: '6.57×10⁻³⁴ J·s', optB: '6.0×10⁻³⁴ J·s', optC: '6.63×10⁻³⁴ J·s', optD: '7.0×10⁻³⁴ J·s',
          hint1: 'eV₁ = hc/λ₁ − φ and eV₂ = hc/λ₂ − φ. Subtract to eliminate φ.',
          hint2: 'e(V₁−V₂) = hc(1/λ₁ − 1/λ₂).',
          hint3: 'h = e(1.85−0.82) / [c×(1/300nm − 1/400nm)] ≈ 6.57×10⁻³⁴ J·s.',
          answer: 'A', level: 3,
        },
      ],

    },
  },

  // ══════════════════════════════════════════════════════════
  // CHEMISTRY
  // ══════════════════════════════════════════════════════════
  Chemistry: {
    icon: '⚗️',
    topics: {

      'Atomic Structure': [
        {
          question: 'Total number of nodes in the 3p orbital:',
          optA: '1', optB: '2', optC: '3', optD: '4',
          hint1: 'Total nodes = n − 1.',
          hint2: 'Radial nodes = n − l − 1; angular nodes = l.',
          hint3: 'For 3p (n=3, l=1): radial = 1, angular = 1 → total = 2.',
          answer: 'B', level: 1,
        },
        {
          question: 'Which set of quantum numbers is NOT allowed: (n = 3, l = 3, m = 0)?',
          optA: 'Valid set', optB: 'Not allowed — l cannot equal n', optC: 'Not allowed — m is out of range', optD: 'Valid for a d-orbital',
          hint1: 'For a given n, l can be 0, 1, 2, ..., (n−1) only.',
          hint2: 'For n = 3, maximum allowed l = 2.',
          hint3: 'l = 3 when n = 3 violates the rule → invalid.',
          answer: 'B', level: 1,
        },
        {
          question: 'Energy of electron in He⁺ (Z = 2) for n = 2 using E = −13.6 Z²/n² eV:',
          optA: '−3.4 eV', optB: '−13.6 eV', optC: '−27.2 eV', optD: '−54.4 eV',
          hint1: 'E_n = −13.6 Z²/n² eV.',
          hint2: 'Z = 2, n = 2.',
          hint3: 'E = −13.6 × 4/4 = −13.6 eV.',
          answer: 'B', level: 2,
        },
        {
          question: 'The correct electron configuration of Cu (Z = 29):',
          optA: '[Ar] 3d⁹ 4s²', optB: '[Ar] 3d¹⁰ 4s¹', optC: '[Ar] 3d⁸ 4s²', optD: '[Ar] 3d¹⁰ 4s²',
          hint1: 'Expected configuration is [Ar] 3d⁹ 4s², but there is an exception.',
          hint2: 'Completely filled d-orbitals (3d¹⁰) are extra stable.',
          hint3: 'One electron shifts from 4s → 3d: [Ar] 3d¹⁰ 4s¹.',
          answer: 'B', level: 2,
        },
        {
          question: '[PYQ JEE Adv.] Ratio of de Broglie wavelength of electron to proton (λ_e/λ_p) accelerated through the same potential difference V:',
          optA: '1/43', optB: '43', optC: '1836', optD: '√1836',
          hint1: 'λ = h/√(2mqV); for same charge and V, λ ∝ 1/√m.',
          hint2: 'λ_e/λ_p = √(m_p/m_e).',
          hint3: 'm_p/m_e ≈ 1836, so ratio ≈ √1836 ≈ 43.',
          answer: 'B', level: 3,
        },
        {
          question: 'According to Heisenberg\'s uncertainty principle, if the position of an electron is measured exactly, its momentum:',
          optA: 'Is also known exactly', optB: 'Is completely uncertain', optC: 'Is zero', optD: 'Is quantised',
          hint1: 'Δx · Δp ≥ h/4π.',
          hint2: 'If Δx → 0 (exact position), then Δp → ∞.',
          hint3: 'Momentum becomes completely uncertain when position is exactly known.',
          answer: 'B', level: 1,
        },
        {
          question: 'Maximum number of electrons in the M shell (n = 3):',
          optA: '8', optB: '16', optC: '18', optD: '32',
          hint1: 'Maximum electrons in a shell = 2n².',
          hint2: 'n = 3.',
          hint3: '2 × 9 = 18.',
          answer: 'C', level: 1,
        },
        {
          question: 'Number of unpaired electrons in Cr (Z = 24) in its ground state:',
          optA: '4', optB: '5', optC: '6', optD: '2',
          hint1: 'Cr has an anomalous configuration due to stability of half-filled d.',
          hint2: 'Cr: [Ar] 3d⁵ 4s¹ (not [Ar] 3d⁴ 4s²).',
          hint3: '3d⁵ (5 unpaired) + 4s¹ (1 unpaired) = 6 unpaired electrons.',
          answer: 'C', level: 2,
        },
        {
          question: 'Energy of a photon of wavelength 600 nm (h = 6.63×10⁻³⁴ J·s, c = 3×10⁸ m/s):',
          optA: '2.07 eV', optB: '3.4 eV', optC: '1.2 eV', optD: '4.1 eV',
          hint1: 'E = hc/λ.',
          hint2: 'E = (6.63×10⁻³⁴ × 3×10⁸) / (600×10⁻⁹) = 3.315×10⁻¹⁹ J.',
          hint3: 'In eV: 3.315×10⁻¹⁹ / 1.6×10⁻¹⁹ ≈ 2.07 eV.',
          answer: 'A', level: 2,
        },
        {
          question: '[PYQ JEE Adv.] Which series of hydrogen spectral lines falls in the visible region?',
          optA: 'Lyman', optB: 'Balmer', optC: 'Paschen', optD: 'Brackett',
          hint1: 'Different series correspond to different final energy levels (n_f).',
          hint2: 'Lyman (n_f=1) — UV; Paschen (n_f=3) — infrared.',
          hint3: 'Balmer series (n_f = 2) lies in the visible region (400–700 nm).',
          answer: 'B', level: 3,
        },
      ],

      'Chemical Bonding': [
        {
          question: 'Shape of SF₆ molecule:',
          optA: 'Trigonal bipyramidal', optB: 'Octahedral', optC: 'Square planar', optD: 'Tetrahedral',
          hint1: 'Count bond pairs and lone pairs on S.',
          hint2: 'SF₆: S forms 6 bonds, no lone pairs.',
          hint3: '6 bond pairs, 0 lone pairs → octahedral geometry.',
          answer: 'B', level: 1,
        },
        {
          question: 'Which molecule has the highest bond order among N₂, O₂, F₂, Ne₂?',
          optA: 'F₂', optB: 'O₂', optC: 'N₂', optD: 'Ne₂',
          hint1: 'Bond order = (bonding e⁻ − antibonding e⁻) / 2.',
          hint2: 'N≡N (triple, BO=3), O=O (double, BO=2), F−F (single, BO=1), Ne₂ (BO=0).',
          hint3: 'N₂ has bond order 3 — the highest.',
          answer: 'C', level: 1,
        },
        {
          question: 'Number of lone pairs on Xe in XeF₂:',
          optA: '2', optB: '3', optC: '4', optD: '1',
          hint1: 'Xe has 8 valence electrons; 2 are used in bonding with F.',
          hint2: 'Remaining 6 electrons = 3 lone pairs.',
          hint3: '2 bond pairs + 3 lone pairs → linear geometry (VSEPR).',
          answer: 'B', level: 2,
        },
        {
          question: 'Among ethane, ethene, ethyne, benzene — which has the shortest C–C bond?',
          optA: 'Ethane', optB: 'Ethene', optC: 'Ethyne', optD: 'Benzene',
          hint1: 'Bond length decreases as bond order increases.',
          hint2: 'C−C=1, C=C=2, C≡C=3, C₆H₆ intermediate ≈1.5.',
          hint3: 'Ethyne (C≡C) has bond order 3 → shortest bond ≈ 1.20 Å.',
          answer: 'C', level: 2,
        },
        {
          question: '[PYQ JEE Adv.] Formal charge on N in NO₃⁻ (structure with one N=O double bond and two N–O single bonds):',
          optA: '0', optB: '+1', optC: '−1', optD: '+2',
          hint1: 'FC = Valence e⁻ − Lone pair e⁻ − ½(Bond e⁻).',
          hint2: 'N has 4 bonds (8 bonding e⁻) and 0 lone pairs in this resonance structure.',
          hint3: 'FC(N) = 5 − 0 − ½(8) = 5 − 4 = +1.',
          answer: 'B', level: 3,
        },
        {
          question: 'Hybridisation of carbon in ethyne (acetylene, HC≡CH):',
          optA: 'sp³', optB: 'sp²', optC: 'sp', optD: 'sp³d',
          hint1: 'Count the number of sigma bonds and lone pairs on carbon.',
          hint2: 'Each C in HC≡CH has 2 sigma bonds (one to H, one to other C) and 0 lone pairs.',
          hint3: '2 regions of electron density → sp hybridisation, linear geometry.',
          answer: 'C', level: 1,
        },
        {
          question: 'Bond angle in water (H₂O) is approximately 104.5°. Why is it less than the tetrahedral angle (109.5°)?',
          optA: 'Bond pair–bond pair repulsion is stronger than lone pair–bond pair', optB: 'Lone pair–lone pair repulsion is stronger, compressing the bond angle', optC: 'H–H repulsion reduces the angle', optD: 'O uses sp² hybridisation',
          hint1: 'O in H₂O has 2 bond pairs and 2 lone pairs in sp³ hybridisation.',
          hint2: 'Order of repulsion: lp–lp > lp–bp > bp–bp.',
          hint3: '2 lone pairs exert strong repulsions, pushing bond pairs closer → angle < 109.5°.',
          answer: 'B', level: 1,
        },
        {
          question: 'BF₃ acts as a Lewis acid because:',
          optA: 'It can donate a proton', optB: 'It has an empty p-orbital and can accept an electron pair', optC: 'F is electronegative', optD: 'It forms ionic bonds',
          hint1: 'Lewis acid = electron pair acceptor; Lewis base = electron pair donor.',
          hint2: 'B in BF₃ has only 3 bond pairs and an empty p-orbital.',
          hint3: 'This empty orbital accepts electron pairs from Lewis bases → BF₃ is a Lewis acid.',
          answer: 'B', level: 2,
        },
        {
          question: 'CO₂ has zero dipole moment but H₂O has a large dipole moment. The reason is:',
          optA: 'CO₂ has stronger bonds', optB: 'CO₂ is linear and symmetric, H₂O is bent', optC: 'CO₂ has more electrons', optD: 'H₂O has ionic bonds',
          hint1: 'Dipole moment depends on both bond polarity and molecular geometry.',
          hint2: 'In CO₂ (linear): the two C=O dipoles are equal and opposite, cancelling out.',
          hint3: 'In H₂O (bent): the two O–H dipoles add up rather than cancel → net dipole.',
          answer: 'B', level: 2,
        },
        {
          question: '[PYQ JEE Adv.] According to MO theory, O₂ is paramagnetic because:',
          optA: 'It has a triple bond', optB: 'Two electrons occupy degenerate π* antibonding orbitals unpaired', optC: 'Its bond order is 3', optD: 'It has no lone pairs',
          hint1: 'Fill molecular orbitals in order: σ1s, σ*1s, σ2s, σ*2s, σ2p, π2p, π*2p, σ*2p.',
          hint2: 'O₂ has 16 electrons. The last two go into the two degenerate π*2p orbitals (one each by Hund\'s rule).',
          hint3: '2 unpaired electrons in π* → paramagnetic. Bond order = (8−4)/2 = 2.',
          answer: 'B', level: 3,
        },
      ],

      'Thermodynamics': [
        {
          question: 'For an ideal gas undergoing an isothermal process, which statement is correct?',
          optA: 'ΔU = 0, Q = 0', optB: 'ΔU = 0, Q = W', optC: 'ΔU = W, Q = 0', optD: 'ΔU = Q = W',
          hint1: 'Isothermal → temperature constant.',
          hint2: 'For ideal gas, ΔU depends only on T: ΔT = 0 → ΔU = 0.',
          hint3: 'From first law: ΔU = Q − W → Q = W when ΔU = 0.',
          answer: 'B', level: 1,
        },
        {
          question: 'Standard enthalpy of combustion of CH₄ = −890 kJ/mol. Heat released by burning 8 g (M = 16 g/mol):',
          optA: '890 kJ', optB: '445 kJ', optC: '222.5 kJ', optD: '1780 kJ',
          hint1: 'Find moles of CH₄ first.',
          hint2: 'moles = 8/16 = 0.5 mol.',
          hint3: 'Heat = 0.5 × 890 = 445 kJ.',
          answer: 'B', level: 1,
        },
        {
          question: 'ΔHf(H₂O, l) = −286 kJ/mol; ΔHf(H₂O, g) = −242 kJ/mol. Enthalpy of vaporisation of water:',
          optA: '44 kJ/mol', optB: '528 kJ/mol', optC: '−44 kJ/mol', optD: '242 kJ/mol',
          hint1: 'Hess\'s law: ΔH_vap = ΔHf(H₂O, g) − ΔHf(H₂O, l).',
          hint2: '= −242 − (−286).',
          hint3: '= +44 kJ/mol (endothermic — vaporisation requires energy).',
          answer: 'A', level: 2,
        },
        {
          question: 'For spontaneity at constant T and P, the necessary and sufficient condition is:',
          optA: 'ΔH < 0', optB: 'ΔS > 0', optC: 'ΔG < 0', optD: 'ΔU < 0',
          hint1: 'Neither ΔH < 0 nor ΔS > 0 alone guarantees spontaneity.',
          hint2: 'ΔG = ΔH − TΔS combines both effects.',
          hint3: 'A process is spontaneous at constant T and P if ΔG < 0.',
          answer: 'C', level: 2,
        },
        {
          question: '[PYQ JEE Adv.] 1 mol ideal gas (γ = 5/3) expands adiabatically from P₁ = 10 atm, T₁ = 600 K to P₂ = 1 atm. Final temperature:',
          optA: '60 K', optB: '150 K', optC: '239 K', optD: '300 K',
          hint1: 'Use adiabatic relation: T₂/T₁ = (P₂/P₁)^((γ−1)/γ).',
          hint2: '(γ−1)/γ = 2/5; T₂ = 600 × (0.1)^(2/5).',
          hint3: 'T₂ = 600 / 10^(0.4) ≈ 600 / 2.512 ≈ 239 K.',
          answer: 'C', level: 3,
        },
        {
          question: 'A system absorbs 500 J of heat and does 200 J of work on surroundings. Change in internal energy ΔU:',
          optA: '700 J', optB: '−300 J', optC: '300 J', optD: '200 J',
          hint1: 'First law of thermodynamics: ΔU = Q − W.',
          hint2: 'Q = +500 J (absorbed), W = +200 J (done by system).',
          hint3: 'ΔU = 500 − 200 = 300 J.',
          answer: 'C', level: 1,
        },
        {
          question: 'For an ideal gas, the relation Cp − Cv = R means: if Cv = 5R/2, then γ (= Cp/Cv) is:',
          optA: '1.2', optB: '1.4', optC: '1.67', optD: '2.0',
          hint1: 'Cp = Cv + R.',
          hint2: 'Cp = 5R/2 + R = 7R/2.',
          hint3: 'γ = Cp/Cv = (7R/2) / (5R/2) = 7/5 = 1.4.',
          answer: 'B', level: 1,
        },
        {
          question: 'Hess\'s law states that enthalpy change of a reaction is:',
          optA: 'Always positive', optB: 'Independent of temperature', optC: 'Independent of the path taken', optD: 'Equal to the entropy change',
          hint1: 'Enthalpy is a state function.',
          hint2: 'State functions depend only on initial and final states, not on the path.',
          hint3: 'Hess\'s law: ΔH is path-independent → can add/subtract equations.',
          answer: 'C', level: 1,
        },
        {
          question: 'At what temperature does a reaction with ΔH = −100 kJ/mol and ΔS = −200 J/(mol·K) become non-spontaneous?',
          optA: 'Above 500 K', optB: 'Below 500 K', optC: 'At all temperatures', optD: 'Never non-spontaneous',
          hint1: 'ΔG = ΔH − TΔS. Non-spontaneous when ΔG > 0.',
          hint2: 'ΔG = 0 at T_eq = ΔH/ΔS = 100000/200 = 500 K.',
          hint3: 'For T > 500 K: −TΔS term (positive, since ΔS<0) dominates → ΔG > 0 → non-spontaneous.',
          answer: 'A', level: 2,
        },
        {
          question: '[PYQ JEE Adv.] For the process H₂O(l) → H₂O(g) at 373 K and 1 atm, which is true?',
          optA: 'ΔG > 0, ΔS > 0', optB: 'ΔG = 0, ΔS > 0', optC: 'ΔG < 0, ΔS < 0', optD: 'ΔG = 0, ΔS < 0',
          hint1: 'At the boiling point (373 K, 1 atm) water and steam are in equilibrium.',
          hint2: 'At equilibrium: ΔG = 0.',
          hint3: 'Vaporisation is endothermic, disorder increases: ΔS > 0. So ΔG = 0, ΔS > 0.',
          answer: 'B', level: 3,
        },
      ],

      'Electrochemistry': [
        {
          question: 'How many moles of H₂ are produced at the cathode by passage of 2 Faradays through H₂O?',
          optA: '0.5 mol', optB: '1 mol', optC: '2 mol', optD: '4 mol',
          hint1: 'Cathode reaction: 2H⁺ + 2e⁻ → H₂ (requires 2 F per mole).',
          hint2: '2 Faradays = 2 moles of electrons.',
          hint3: '2 mol e⁻ → 1 mol H₂.',
          answer: 'B', level: 1,
        },
        {
          question: 'E°(Zn²⁺/Zn) = −0.76 V, E°(Cu²⁺/Cu) = +0.34 V. E°cell for Zn|Zn²⁺||Cu²⁺|Cu:',
          optA: '0.42 V', optB: '1.10 V', optC: '−1.10 V', optD: '0.76 V',
          hint1: 'E°cell = E°cathode − E°anode.',
          hint2: 'Cathode (reduction): Cu²⁺/Cu = +0.34 V; Anode (oxidation): Zn/Zn²⁺, E°anode = −0.76 V.',
          hint3: 'E°cell = 0.34 − (−0.76) = 1.10 V.',
          answer: 'B', level: 1,
        },
        {
          question: 'Kohlrausch\'s law (Λm = Λ°m − K√C) applies to:',
          optA: 'Weak electrolytes at high dilution', optB: 'Strong electrolytes at low concentration', optC: 'Non-electrolytes', optD: 'All electrolytes equally',
          hint1: 'This linear relation between Λm and √C must hold experimentally.',
          hint2: 'Weak electrolytes show a sharp non-linear rise at high dilution.',
          hint3: 'The linear law holds only for strong electrolytes (complete dissociation).',
          answer: 'B', level: 2,
        },
        {
          question: 'Electrolysis of CuSO₄ with Cu electrodes deposits 0.635 g Cu (M = 63.5 g/mol, F = 96500 C). Charge passed:',
          optA: '965 C', optB: '1930 C', optC: '3860 C', optD: '96500 C',
          hint1: 'Cu²⁺ + 2e⁻ → Cu (n-factor = 2).',
          hint2: 'moles of Cu = 0.635/63.5 = 0.01 mol; moles of e⁻ = 0.01 × 2 = 0.02.',
          hint3: 'Q = 0.02 × 96500 = 1930 C.',
          answer: 'B', level: 2,
        },
        {
          question: '[PYQ JEE Adv.] For Mg|Mg²⁺||Cu²⁺|Cu, E°cell = 2.71 V at 298 K. ΔG° and log K (F = 96500, 0.0591 V/decade):',
          optA: 'ΔG° ≈ −523 kJ/mol, log K ≈ 91.7', optB: 'ΔG° ≈ −261 kJ/mol, log K ≈ 45', optC: 'ΔG° ≈ +523 kJ/mol, log K ≈ −91.7', optD: 'ΔG° ≈ −523 kJ/mol, log K ≈ 45',
          hint1: 'ΔG° = −nFE°cell, n = 2.',
          hint2: 'ΔG° = −2 × 96500 × 2.71 ≈ −523 kJ/mol.',
          hint3: 'log K = nE° / 0.0591 = 2 × 2.71 / 0.0591 ≈ 91.7.',
          answer: 'A', level: 3,
        },
        {
          question: 'Standard hydrogen electrode (SHE) is assigned a potential of:',
          optA: '+1.0 V', optB: '−1.0 V', optC: '0.0 V', optD: '+0.5 V',
          hint1: 'The SHE is the universal reference electrode.',
          hint2: 'All standard electrode potentials are measured relative to SHE.',
          hint3: 'By convention, E°(SHE) = 0.00 V.',
          answer: 'C', level: 1,
        },
        {
          question: 'In an electrolytic cell, oxidation occurs at the:',
          optA: 'Cathode', optB: 'Anode', optC: 'Both electrodes', optD: 'Neither electrode',
          hint1: 'Remember: An Ox, Red Cat (Anode = Oxidation, Cathode = Reduction).',
          hint2: 'This rule applies to both galvanic and electrolytic cells.',
          hint3: 'Oxidation (loss of electrons) always occurs at the anode.',
          answer: 'B', level: 1,
        },
        {
          question: 'For the Nernst equation at 298 K: E = E° − (0.0591/n) log Q. If Q > K, then:',
          optA: 'E > E° and reaction is spontaneous', optB: 'E < 0 and reaction is non-spontaneous', optC: 'E is unaffected', optD: 'E > 0 always',
          hint1: 'When Q > K, the reaction has gone past equilibrium in the forward direction.',
          hint2: 'Q > K → log Q > log K → E = E° − (0.0591/n) log Q is reduced below zero.',
          hint3: 'E < 0 means the reaction is non-spontaneous in the forward direction.',
          answer: 'B', level: 2,
        },
        {
          question: 'Molar conductivity of a strong electrolyte ______ on dilution:',
          optA: 'Decreases', optB: 'Increases', optC: 'Remains constant', optD: 'First increases then decreases',
          hint1: 'At higher dilution, inter-ionic interactions decrease.',
          hint2: 'More ions are free to move → higher ionic mobility.',
          hint3: 'Molar conductivity increases with dilution for strong electrolytes, approaching Λ°m.',
          answer: 'B', level: 2,
        },
        {
          question: '[PYQ JEE Adv.] In the electrolysis of dilute H₂SO₄, 2.7 g of Ag is deposited at cathode when the same current passes through another cell with AgNO₃ solution (M_Ag = 108, M_Cu = 64, valency of Cu = 2). Mass of Cu deposited:',
          optA: '0.4 g', optB: '0.8 g', optC: '1.6 g', optD: '3.2 g',
          hint1: 'Faraday\'s 2nd law: for the same charge, mass deposited ∝ equivalent weight.',
          hint2: 'Equiv. wt of Ag = 108/1 = 108; Equiv. wt of Cu = 64/2 = 32.',
          hint3: 'm_Cu / m_Ag = (eq. wt of Cu) / (eq. wt of Ag) → m_Cu = 2.7 × 32/108 = 0.8 g.',
          answer: 'B', level: 3,
        },
      ],

      'Organic Chemistry': [
        {
          question: 'In 2-methylbutane, the count of primary (1°), secondary (2°), and tertiary (3°) carbons:',
          optA: '1° = 3, 2° = 1, 3° = 1', optB: '1° = 2, 2° = 2, 3° = 1', optC: '1° = 2, 2° = 1, 3° = 2', optD: '1° = 3, 2° = 2, 3° = 0',
          hint1: 'Primary C (1°): bonded to 1 other C; 2°: 2 C; 3°: 3 C.',
          hint2: 'Structure: CH₃−CH(CH₃)−CH₂−CH₃.',
          hint3: '3 primary C (three CH₃ groups), 1 secondary C (CH₂), 1 tertiary C (CH).',
          answer: 'A', level: 1,
        },
        {
          question: 'Correct IUPAC name for CH₃−CH=CH−CH₃:',
          optA: '2-butene', optB: 'But-2-ene', optC: '2-methylpropene', optD: 'But-1-ene',
          hint1: 'Identify the parent chain and position of double bond.',
          hint2: '4-carbon chain with double bond starting at C2.',
          hint3: 'Modern IUPAC: but-2-ene (locant before suffix).',
          answer: 'B', level: 1,
        },
        {
          question: 'Major product of SN1 reaction of (CH₃)₃CBr with H₂O:',
          optA: '2-methylpropene', optB: '(CH₃)₃COH', optC: '(CH₃)₂C=CH₂', optD: '(CH₃)₃CCl',
          hint1: 'Tertiary halide → SN1 (stable 3° carbocation).',
          hint2: '(CH₃)₃CBr → (CH₃)₃C⁺ + Br⁻.',
          hint3: 'H₂O attacks carbocation → (CH₃)₃C−OH₂⁺ → loses H⁺ → (CH₃)₃COH.',
          answer: 'B', level: 2,
        },
        {
          question: 'HBr adds to propene (CH₃CH=CH₂) by Markovnikov\'s rule. Major product:',
          optA: '1-bromopropane', optB: '2-bromopropane', optC: 'Propane', optD: 'Allyl bromide',
          hint1: 'Markovnikov: H⁺ adds to carbon bearing more H atoms.',
          hint2: 'The CH₂ end gets H⁺; more stable 2° carbocation forms at C2.',
          hint3: 'Br⁻ attacks C2 → 2-bromopropane (CH₃CHBrCH₃).',
          answer: 'B', level: 2,
        },
        {
          question: '[PYQ JEE Adv.] Nitration of benzene: the electrophile and mechanism type are:',
          optA: 'NO₂⁺, nucleophilic substitution', optB: 'NO₂⁻, electrophilic addition', optC: 'NO₂⁺, electrophilic aromatic substitution', optD: 'HNO₃, free radical',
          hint1: 'HNO₃ + H₂SO₄ → NO₂⁺ (nitronium ion) + HSO₄⁻ + H₂O.',
          hint2: 'Benzene\'s π-cloud attacks the electrophile NO₂⁺.',
          hint3: 'Wheland intermediate forms, then H⁺ is lost to restore aromaticity — EAS.',
          answer: 'C', level: 3,
        },
        {
          question: 'Tollens\' reagent (ammoniacal AgNO₃) gives a silver mirror with:',
          optA: 'Acetone', optB: 'Benzaldehyde', optC: 'Cyclohexanone', optD: 'Diethyl ether',
          hint1: 'Tollens\' test is a test for aldehydes (and alpha-hydroxy ketones).',
          hint2: 'Aldehydes are oxidised by Ag⁺ → Ag (silver mirror).',
          hint3: 'Benzaldehyde is an aldehyde (–CHO group) → gives positive Tollens\' test.',
          answer: 'B', level: 1,
        },
        {
          question: 'Lucas test (ZnCl₂/HCl) on 1°, 2°, and 3° alcohols at room temperature: correct order of reactivity:',
          optA: '1° > 2° > 3°', optB: '3° > 2° > 1°', optC: '2° > 1° > 3°', optD: 'All react equally',
          hint1: 'Lucas test involves SN1 reaction (carbocation intermediate).',
          hint2: 'Stability of carbocation: 3° > 2° > 1°.',
          hint3: '3° alcohol reacts immediately (turbidity), 2° reacts in ~5 min, 1° does not react at room temperature.',
          answer: 'B', level: 1,
        },
        {
          question: 'Aldol condensation of acetaldehyde (CH₃CHO) in dilute NaOH gives:',
          optA: 'Acetic acid', optB: '3-hydroxybutanal', optC: 'Ethanol', optD: 'Crotonaldehyde only',
          hint1: 'In aldol reaction, one molecule acts as nucleophile (enolate) attacking another\'s carbonyl.',
          hint2: 'CH₃CHO + enolate of CH₃CHO → β-hydroxy aldehyde.',
          hint3: 'Product: CH₃CH(OH)CH₂CHO = 3-hydroxybutanal (β-hydroxybutyraldehyde).',
          answer: 'B', level: 2,
        },
        {
          question: 'Grignard reagent (CH₃MgBr) reacts with CO₂ followed by H₃O⁺ to give:',
          optA: 'Methanol', optB: 'Ethanol', optC: 'Acetic acid', optD: 'Formic acid',
          hint1: 'Grignard reagents react with CO₂ to form carboxylate salt after workup.',
          hint2: 'CH₃MgBr + CO₂ → CH₃COOMgBr.',
          hint3: 'After acid hydrolysis: CH₃COOH = acetic acid.',
          answer: 'C', level: 2,
        },
        {
          question: '[PYQ JEE Adv.] In the Diels-Alder reaction, the diene must be in the:',
          optA: 's-trans conformation', optB: 's-cis conformation', optC: 'Chair conformation', optD: 'Anti conformation',
          hint1: 'Diels-Alder is a [4+2] cycloaddition reaction between a diene and a dienophile.',
          hint2: 'The reaction requires the diene to adopt a specific conformation for orbital overlap.',
          hint3: 's-cis conformation allows C1 and C4 of the diene to be close enough to bond with the dienophile.',
          answer: 'B', level: 3,
        },
      ],

    },
  },

  // ══════════════════════════════════════════════════════════
  // MATHS
  // ══════════════════════════════════════════════════════════
  Maths: {
    icon: '∑',
    topics: {

      'Limits & Continuity': [
        {
          question: 'lim(x→0) sin(3x) / sin(2x) = ?',
          optA: '1', optB: '3/2', optC: '2/3', optD: '0',
          hint1: 'Use standard limit: lim(x→0) sinx/x = 1.',
          hint2: 'Write as (sin3x/3x) × (3x/2x) × (2x/sin2x).',
          hint3: '= 1 × (3/2) × 1 = 3/2.',
          answer: 'B', level: 1,
        },
        {
          question: 'f(x) = |x|/x for x ≠ 0. Is f continuous at x = 0?',
          optA: 'Yes, defining f(0) = 0 makes it continuous', optB: 'No, left and right limits differ', optC: 'Yes, if we define f(0) = 1', optD: 'Continuous everywhere',
          hint1: 'Check left-hand and right-hand limits at x = 0.',
          hint2: 'For x > 0: |x|/x = 1; for x < 0: |x|/x = −1.',
          hint3: 'LHL = −1 ≠ RHL = 1 → discontinuous at x = 0.',
          answer: 'B', level: 1,
        },
        {
          question: 'lim(x→0) (1 − cos x) / x² = ?',
          optA: '0', optB: '1', optC: '1/2', optD: '2',
          hint1: 'Use Taylor expansion: cos x ≈ 1 − x²/2 + ...',
          hint2: '(1 − cosx)/x² ≈ (x²/2)/x² = 1/2.',
          hint3: 'Or apply L\'Hôpital twice: sinx/2x → cosx/2 → 1/2.',
          answer: 'C', level: 2,
        },
        {
          question: 'f(x) = (x² − 9)/(x − 3) for x ≠ 3, and f(3) = k for continuity. Then k = ?',
          optA: '3', optB: '6', optC: '9', optD: '0',
          hint1: 'For continuity, f(3) = lim(x→3) f(x).',
          hint2: 'Factor: (x² − 9)/(x − 3) = (x + 3)(x − 3)/(x − 3) = x + 3.',
          hint3: 'lim(x→3)(x + 3) = 6, so k = 6.',
          answer: 'B', level: 2,
        },
        {
          question: 'lim(x→∞) (1 + 2/x)^x = ?',
          optA: 'e', optB: 'e²', optC: '2', optD: '1',
          hint1: 'Recognise the standard form: lim(1 + t)^(1/t) = e as t → 0.',
          hint2: 'Write (1 + 2/x)^x = [(1 + 2/x)^(x/2)]².',
          hint3: 'As x → ∞, (1 + 2/x)^(x/2) → e, so limit = e².',
          answer: 'B', level: 3,
        },
        {
          question: 'lim(x→0) (eˣ − 1) / x = ?',
          optA: '0', optB: 'e', optC: '1', optD: '∞',
          hint1: 'This is a standard result — try L\'Hôpital\'s rule.',
          hint2: 'Apply L\'Hôpital: d/dx(eˣ − 1) = eˣ; d/dx(x) = 1.',
          hint3: 'lim(x→0) eˣ/1 = e⁰ = 1.',
          answer: 'C', level: 1,
        },
        {
          question: 'lim(x→2) (x² − 4) / (x − 2) = ?',
          optA: '0', optB: '2', optC: '4', optD: 'Does not exist',
          hint1: 'Direct substitution gives 0/0 — factorise.',
          hint2: 'x² − 4 = (x − 2)(x + 2).',
          hint3: '(x + 2)(x − 2)/(x − 2) = x + 2 → lim = 4.',
          answer: 'C', level: 1,
        },
        {
          question: 'If f(x) = x² sin(1/x) for x ≠ 0, and f(0) = 0, then f is:',
          optA: 'Discontinuous at 0', optB: 'Continuous but not differentiable at 0', optC: 'Continuous and differentiable at 0', optD: 'Differentiable but not continuous',
          hint1: '|f(x)| = |x²||sin(1/x)| ≤ x² → 0 as x → 0. So f is continuous at 0.',
          hint2: "f'(0) = lim(x→0) [x² sin(1/x) − 0]/x = lim x sin(1/x).",
          hint3: '|x sin(1/x)| ≤ |x| → 0, so f\'(0) = 0. Continuous AND differentiable at 0.',
          answer: 'C', level: 2,
        },
        {
          question: 'lim(x→π/2) (1 − sinx) / cos²x = ?',
          optA: '0', optB: '1/2', optC: '1', optD: '∞',
          hint1: 'Direct substitution gives 0/0. Apply L\'Hôpital\'s rule.',
          hint2: 'd/dx(1 − sinx) = −cosx; d/dx(cos²x) = −2cosx sinx.',
          hint3: 'Limit = (−cosx)/(−2cosx sinx) = 1/(2sinx) → 1/(2×1) = 1/2.',
          answer: 'B', level: 2,
        },
        {
          question: '[PYQ JEE Adv.] lim(x→0) [tan x − sin x] / x³ = ?',
          optA: '0', optB: '1', optC: '1/2', optD: '1/3',
          hint1: 'Use series expansions: tan x = x + x³/3 + ...; sin x = x − x³/6 + ...',
          hint2: 'tan x − sin x = (x + x³/3) − (x − x³/6) = x³(1/3 + 1/6) = x³/2.',
          hint3: '(tan x − sin x)/x³ → 1/2 as x → 0.',
          answer: 'C', level: 3,
        },
      ],

      'Integration': [
        {
          question: '∫ sin²x dx = ?',
          optA: '−cos²x + C', optB: 'x/2 − sin(2x)/4 + C', optC: '−sinx cosx + C', optD: 'cos²x/2 + C',
          hint1: 'Use identity: sin²x = (1 − cos 2x)/2.',
          hint2: '∫(1 − cos 2x)/2 dx = x/2 − sin2x/4 + C.',
          hint3: '= x/2 − sin(2x)/4 + C.',
          answer: 'B', level: 1,
        },
        {
          question: '∫₀¹ xeˣ dx = ?',
          optA: 'e', optB: '1', optC: 'e − 1', optD: '2e − 1',
          hint1: 'Use integration by parts: ∫u dv = uv − ∫v du.',
          hint2: 'Let u = x, dv = eˣdx → du = dx, v = eˣ.',
          hint3: '[xeˣ − eˣ]₀¹ = (e − e) − (0 − 1) = 1.',
          answer: 'B', level: 1,
        },
        {
          question: '∫ dx / (x² + 2x + 5) = ?',
          optA: 'arctan(x + 1) + C', optB: '½ arctan((x+1)/2) + C', optC: 'ln(x² + 2x + 5) + C', optD: 'arctan(x + 2) + C',
          hint1: 'Complete the square: x² + 2x + 5 = (x+1)² + 4.',
          hint2: 'Use ∫dx/(u² + a²) = (1/a) arctan(u/a), with u = x+1, a = 2.',
          hint3: 'Answer = ½ arctan((x+1)/2) + C.',
          answer: 'B', level: 2,
        },
        {
          question: 'Area enclosed between y = x² − 4 and the x-axis from x = 0 to x = 2:',
          optA: '8/3', optB: '16/3', optC: '4', optD: '8',
          hint1: 'x² − 4 < 0 on (0, 2), so take the absolute value of the integral.',
          hint2: 'Area = |∫₀²(x² − 4) dx|.',
          hint3: '|[x³/3 − 4x]₀²| = |8/3 − 8| = 16/3.',
          answer: 'B', level: 2,
        },
        {
          question: '[PYQ JEE Adv.] ∫₀^(π/2) log(sin x) dx = ?',
          optA: '0', optB: 'π/2', optC: '−(π/2) ln 2', optD: '(π/2) ln 2',
          hint1: 'Use King\'s property: I = ∫₀^(π/2) log(sin x) dx = ∫₀^(π/2) log(cos x) dx.',
          hint2: '2I = ∫₀^(π/2) log(sin x cos x) dx = ∫₀^(π/2) [log(sin 2x) − log 2] dx.',
          hint3: '2I = I − (π/2) log 2 → I = −(π/2) ln 2.',
          answer: 'C', level: 3,
        },
        {
          question: '∫ cos x dx = ?',
          optA: '−sin x + C', optB: 'sin x + C', optC: 'tan x + C', optD: '−cos x + C',
          hint1: 'Recall the basic integration rule for cosine.',
          hint2: 'd/dx(sin x) = cos x.',
          hint3: 'Therefore ∫cos x dx = sin x + C.',
          answer: 'B', level: 1,
        },
        {
          question: '∫₀² x² dx = ?',
          optA: '4/3', optB: '8/3', optC: '2', optD: '4',
          hint1: 'Use power rule: ∫xⁿ dx = xⁿ⁺¹/(n+1).',
          hint2: '∫₀² x² dx = [x³/3]₀².',
          hint3: '= 8/3 − 0 = 8/3.',
          answer: 'B', level: 1,
        },
        {
          question: '∫ 2x / (1 + x²) dx = ?',
          optA: 'ln|1 + x| + C', optB: 'ln(1 + x²) + C', optC: '2 arctan x + C', optD: '1/(1 + x²) + C',
          hint1: 'Notice that the numerator is the derivative of the denominator.',
          hint2: 'Let u = 1 + x², then du = 2x dx.',
          hint3: '∫du/u = ln|u| + C = ln(1 + x²) + C.',
          answer: 'B', level: 2,
        },
        {
          question: 'Area enclosed between y = x and y = x² (between their intersection points):',
          optA: '1/6', optB: '1/3', optC: '1/2', optD: '1/4',
          hint1: 'Find intersections: x = x² → x = 0 and x = 1.',
          hint2: 'Area = ∫₀¹ (x − x²) dx (line is above parabola on [0,1]).',
          hint3: '[x²/2 − x³/3]₀¹ = 1/2 − 1/3 = 1/6.',
          answer: 'A', level: 2,
        },
        {
          question: '[PYQ JEE Adv.] ∫ log x dx = ?',
          optA: '1/x + C', optB: 'x log x − x + C', optC: 'x log x + C', optD: 'log x / x + C',
          hint1: 'Use integration by parts: ∫u dv = uv − ∫v du.',
          hint2: 'Let u = log x, dv = dx → du = (1/x)dx, v = x.',
          hint3: '∫log x dx = x log x − ∫x × (1/x) dx = x log x − x + C.',
          answer: 'B', level: 3,
        },
      ],

      'Matrices & Determinants': [
        {
          question: 'If A = [[2, 3], [1, 4]], then det(A) = ?',
          optA: '5', optB: '11', optC: '8', optD: '3',
          hint1: 'For 2×2 matrix [[a,b],[c,d]], det = ad − bc.',
          hint2: 'det = 2×4 − 3×1.',
          hint3: '= 8 − 3 = 5.',
          answer: 'A', level: 1,
        },
        {
          question: 'A is a 3×3 matrix with det(A) = 4. Then det(2A) = ?',
          optA: '8', optB: '16', optC: '32', optD: '64',
          hint1: 'Property: det(kA) = kⁿ det(A) for an n×n matrix.',
          hint2: 'n = 3, k = 2: det(2A) = 2³ × det(A).',
          hint3: '= 8 × 4 = 32.',
          answer: 'C', level: 1,
        },
        {
          question: 'If A = [[1,2],[3,4]], then A⁻¹ = ?',
          optA: '[[−2, 1],[3/2, −1/2]]', optB: '[[4, −2],[−3, 1]]', optC: '[[1/2, 1],[3/2, 2]]', optD: 'Does not exist',
          hint1: 'A⁻¹ = (1/det(A)) × adj(A).',
          hint2: 'det(A) = 4 − 6 = −2; adj(A) = [[4,−2],[−3,1]].',
          hint3: 'A⁻¹ = (−1/2)[[4,−2],[−3,1]] = [[−2,1],[3/2,−1/2]].',
          answer: 'A', level: 2,
        },
        {
          question: 'System: x + y = 3, 2x + 2y = 7. Nature of solution:',
          optA: 'Unique solution', optB: 'Infinitely many solutions', optC: 'No solution', optD: 'Two solutions',
          hint1: 'Compute determinant D of the coefficient matrix.',
          hint2: 'D = |1 1; 2 2| = 2 − 2 = 0; check Dₓ = |3 1; 7 2| = 6 − 7 = −1.',
          hint3: 'D = 0 but Dₓ ≠ 0 → inconsistent → no solution.',
          answer: 'C', level: 2,
        },
        {
          question: '[PYQ JEE Adv.] If A = [[0,1],[1,0]], then A¹⁰⁰ = ?',
          optA: '[[0,1],[1,0]]', optB: '[[1,0],[0,1]]', optC: '[[0,100],[100,0]]', optD: '[[100,0],[0,100]]',
          hint1: 'Compute A² first.',
          hint2: 'A² = [[0,1],[1,0]] × [[0,1],[1,0]] = [[1,0],[0,1]] = I.',
          hint3: 'A^(2k) = I; since 100 = 2×50, A¹⁰⁰ = I.',
          answer: 'B', level: 3,
        },
        {
          question: 'For a skew-symmetric matrix A (i.e. Aᵀ = −A) of odd order, det(A) = ?',
          optA: '1', optB: '−1', optC: '0', optD: 'det(Aᵀ)',
          hint1: 'Property: det(Aᵀ) = det(A).',
          hint2: 'Also, det(−A) = (−1)ⁿ det(A) for n×n matrix.',
          hint3: 'Since Aᵀ = −A: det(A) = det(−A) = (−1)ⁿ det(A). For odd n: det(A) = −det(A) → det(A) = 0.',
          answer: 'C', level: 1,
        },
        {
          question: 'Expanding det [[1,2,3],[0,4,5],[1,0,6]] along the first column:',
          optA: '22', optB: '27', optC: '−3', optD: '32',
          hint1: 'Along column 1: det = 1×M₁₁ − 0×M₂₁ + 1×M₃₁.',
          hint2: 'M₁₁ = det[[4,5],[0,6]] = 24; M₃₁ = det[[2,3],[4,5]] = 10−12 = −2.',
          hint3: 'det = 1×24 − 0 + 1×(−2) = 24 − 2 = 22.',
          answer: 'A', level: 1,
        },
        {
          question: 'Eigenvalues of matrix A = [[3,1],[0,3]] are:',
          optA: '3 and 0', optB: '3 and 1', optC: '3 and 3', optD: '1 and 3',
          hint1: 'Eigenvalues satisfy det(A − λI) = 0.',
          hint2: 'det[[3−λ, 1],[0, 3−λ]] = (3−λ)² = 0.',
          hint3: 'λ = 3 (repeated). Both eigenvalues are 3.',
          answer: 'C', level: 2,
        },
        {
          question: 'By Cayley-Hamilton theorem, if characteristic polynomial of A is λ² − 5λ + 6 = 0, then:',
          optA: 'A² = 5A − 6I', optB: 'A² = 5A + 6I', optC: 'A + 5I = 6A²', optD: 'A² − 6A + 5I = 0',
          hint1: 'Cayley-Hamilton: every matrix satisfies its own characteristic equation.',
          hint2: 'Replace λ with A in λ² − 5λ + 6 = 0.',
          hint3: 'A² − 5A + 6I = 0 → A² = 5A − 6I.',
          answer: 'A', level: 2,
        },
        {
          question: '[PYQ JEE Adv.] A is a 3×3 orthogonal matrix (AᵀA = I). Then det(A) is:',
          optA: 'Always 1', optB: 'Always −1', optC: '0 or 1', optD: '+1 or −1',
          hint1: 'Property of determinants: det(AB) = det(A) × det(B).',
          hint2: 'det(AᵀA) = det(Aᵀ) × det(A) = [det(A)]² = det(I) = 1.',
          hint3: '[det(A)]² = 1 → det(A) = ±1.',
          answer: 'D', level: 3,
        },
      ],

      'Complex Numbers': [
        {
          question: '|3 + 4i| = ?',
          optA: '3', optB: '4', optC: '5', optD: '7',
          hint1: '|a + bi| = √(a² + b²).',
          hint2: '|3 + 4i| = √(9 + 16).',
          hint3: '= √25 = 5.',
          answer: 'C', level: 1,
        },
        {
          question: 'Argument of the complex number −1 + i:',
          optA: 'π/4', optB: '3π/4', optC: '−π/4', optD: 'π',
          hint1: 'Use arg(a + bi) adjusted for the correct quadrant.',
          hint2: '−1 + i is in the 2nd quadrant (a < 0, b > 0).',
          hint3: 'arg = π − arctan(1) = π − π/4 = 3π/4.',
          answer: 'B', level: 1,
        },
        {
          question: 'If ω is a complex cube root of unity, 1 + ω + ω² = ?',
          optA: '1', optB: '−1', optC: '0', optD: 'ω',
          hint1: 'The three cube roots of unity satisfy x³ = 1.',
          hint2: 'x³ − 1 = (x − 1)(x² + x + 1) = 0; since ω ≠ 1: ω² + ω + 1 = 0.',
          hint3: 'Therefore 1 + ω + ω² = 0.',
          answer: 'C', level: 2,
        },
        {
          question: '(1 + i)⁸ = ?',
          optA: '8', optB: '16', optC: '−16', optD: '4i',
          hint1: 'Compute (1 + i)² first.',
          hint2: '(1 + i)² = 2i; (1 + i)⁴ = (2i)² = −4.',
          hint3: '(1 + i)⁸ = (−4)² = 16.',
          answer: 'B', level: 2,
        },
        {
          question: '[PYQ JEE Adv.] z₁ = 2 + 3i, z₂ = 1 − i. Express z₁/z₂ in a + bi form:',
          optA: '(−1 + 5i)/2', optB: '(1 + 5i)/2', optC: '(−1 − 5i)/2', optD: '(5 − i)/2',
          hint1: 'Multiply numerator and denominator by the conjugate of z₂.',
          hint2: '(2 + 3i)(1 + i) / [(1 − i)(1 + i)] = (2 + 2i + 3i − 3) / 2.',
          hint3: '= (−1 + 5i) / 2.',
          answer: 'A', level: 3,
        },
        {
          question: 'If z = a + bi, then z + z̄ = ?',
          optA: '2bi', optB: '2a', optC: '2|z|', optD: '0',
          hint1: 'The conjugate z̄ = a − bi.',
          hint2: 'z + z̄ = (a + bi) + (a − bi).',
          hint3: '= 2a (the imaginary parts cancel).',
          answer: 'B', level: 1,
        },
        {
          question: 'By De Moivre\'s theorem, (cos θ + i sin θ)ⁿ = ?',
          optA: 'cos(nθ) − i sin(nθ)', optB: 'cos(nθ) + i sin(nθ)', optC: 'n cos θ + ni sin θ', optD: 'e^(nθ)',
          hint1: 'De Moivre\'s theorem is about powers of complex numbers in polar form.',
          hint2: '(e^(iθ))ⁿ = e^(inθ).',
          hint3: 'e^(inθ) = cos(nθ) + i sin(nθ).',
          answer: 'B', level: 1,
        },
        {
          question: 'Locus of z if |z − 2| = |z + 2|:',
          optA: 'Circle of radius 2', optB: 'x-axis', optC: 'y-axis', optD: 'Line y = x',
          hint1: '|z − 2| = |z + 2| means z is equidistant from the points 2+0i and −2+0i.',
          hint2: 'The locus of a point equidistant from two fixed points is their perpendicular bisector.',
          hint3: 'Midpoint of (2,0) and (−2,0) is origin; bisector is the y-axis (x = 0).',
          answer: 'C', level: 2,
        },
        {
          question: 'The nth roots of unity are:',
          optA: 'n real numbers', optB: 'Points equally spaced on the unit circle', optC: 'All equal to 1', optD: 'Points on a line',
          hint1: 'The nth roots of unity satisfy zⁿ = 1.',
          hint2: 'In polar form: z = e^(2πik/n) for k = 0, 1, ..., n−1.',
          hint3: 'These are n evenly spaced points on the unit circle |z| = 1.',
          answer: 'B', level: 2,
        },
        {
          question: '[PYQ JEE Adv.] The real part of (1 + i)^20 is:',
          optA: '0', optB: '1024', optC: '−1024', optD: '512',
          hint1: 'Convert 1 + i to polar form: |1+i| = √2, arg = π/4.',
          hint2: '(1 + i)^20 = (√2)^20 × e^(i×20×π/4) = 2^10 × e^(5πi) = 1024 × e^(πi).',
          hint3: 'e^(πi) = cosπ + i sinπ = −1 + 0i. So (1+i)^20 = −1024. Real part = −1024.',
          answer: 'C', level: 3,
        },
      ],

      'Probability': [
        {
          question: 'Two dice are rolled. P(sum = 7):',
          optA: '1/12', optB: '1/6', optC: '5/36', optD: '7/36',
          hint1: 'Total outcomes = 6 × 6 = 36.',
          hint2: 'Pairs summing to 7: (1,6),(2,5),(3,4),(4,3),(5,2),(6,1) — 6 pairs.',
          hint3: 'P = 6/36 = 1/6.',
          answer: 'B', level: 1,
        },
        {
          question: 'Bag has 5 red and 3 blue balls. P(drawing 2 red in a row, without replacement):',
          optA: '25/64', optB: '5/14', optC: '5/16', optD: '1/7',
          hint1: 'Use conditional probability (without replacement — dependent events).',
          hint2: 'P(1st red) = 5/8; P(2nd red | 1st red) = 4/7.',
          hint3: 'P = 5/8 × 4/7 = 20/56 = 5/14.',
          answer: 'B', level: 1,
        },
        {
          question: 'P(A) = 0.4, P(B) = 0.3, P(A∩B) = 0.1. P(A∪B) = ?',
          optA: '0.5', optB: '0.6', optC: '0.7', optD: '1.2',
          hint1: 'Use addition rule: P(A∪B) = P(A) + P(B) − P(A∩B).',
          hint2: '= 0.4 + 0.3 − 0.1.',
          hint3: '= 0.6.',
          answer: 'B', level: 2,
        },
        {
          question: 'Binomial distribution with n = 6, p = 1/3. P(X = 2):',
          optA: '15/243', optB: '80/243', optC: '60/243', optD: '20/81',
          hint1: 'P(X = k) = C(n,k) × pᵏ × (1−p)^(n−k).',
          hint2: 'C(6,2) = 15; (1/3)² = 1/9; (2/3)⁴ = 16/81.',
          hint3: 'P = 15 × 1/9 × 16/81 = 240/729 = 80/243.',
          answer: 'B', level: 2,
        },
        {
          question: '[PYQ JEE Adv. — Bayes] Box A: 3 red, 2 white. Box B: 2 red, 3 white. A box is chosen randomly; one ball drawn — it is red. P(it came from Box A):',
          optA: '1/2', optB: '3/5', optC: '2/5', optD: '3/10',
          hint1: 'Use Bayes\' theorem: P(A|Red) = P(A)P(R|A) / P(R).',
          hint2: 'P(R) = ½ × (3/5) + ½ × (2/5) = 1/2.',
          hint3: 'P(A|Red) = (½ × 3/5) / (1/2) = 3/5.',
          answer: 'B', level: 3,
        },
        {
          question: 'For event A, P(A\') = 0.35. Then P(A) = ?',
          optA: '0.35', optB: '0.65', optC: '1.35', optD: '0',
          hint1: 'The complement rule: P(A) + P(A\') = 1.',
          hint2: 'P(A) = 1 − P(A\').',
          hint3: 'P(A) = 1 − 0.35 = 0.65.',
          answer: 'B', level: 1,
        },
        {
          question: 'Two events A and B are mutually exclusive. P(A) = 0.3, P(B) = 0.4. P(A∩B) = ?',
          optA: '0.12', optB: '0.7', optC: '0', optD: '0.1',
          hint1: 'Mutually exclusive means A and B cannot occur together.',
          hint2: 'If A and B are mutually exclusive, they have no common outcomes.',
          hint3: 'P(A∩B) = 0.',
          answer: 'C', level: 1,
        },
        {
          question: 'Events A and B are independent. P(A) = 0.5, P(B) = 0.4. P(A∩B) = ?',
          optA: '0.9', optB: '0.1', optC: '0.2', optD: '0.45',
          hint1: 'For independent events, the joint probability factorises.',
          hint2: 'P(A∩B) = P(A) × P(B).',
          hint3: '= 0.5 × 0.4 = 0.2.',
          answer: 'C', level: 2,
        },
        {
          question: 'P(B|A) = 0.6, P(A) = 0.5, P(B) = 0.4. Using total probability, P(B|A\') = ?',
          optA: '0.1', optB: '0.2', optC: '0.3', optD: '0.5',
          hint1: 'Total probability: P(B) = P(A)P(B|A) + P(A\')P(B|A\').',
          hint2: '0.4 = 0.5 × 0.6 + 0.5 × P(B|A\').',
          hint3: '0.4 = 0.3 + 0.5 × P(B|A\') → P(B|A\') = 0.2.',
          answer: 'B', level: 2,
        },
        {
          question: '[PYQ JEE Adv.] A fair coin is tossed 10 times. P(getting exactly 5 heads):',
          optA: '63/256', optB: '63/512', optC: '252/1024', optD: '1/2',
          hint1: 'Use binomial: P(X=5) = C(10,5) × (1/2)⁵ × (1/2)⁵.',
          hint2: 'C(10,5) = 252; (1/2)^10 = 1/1024.',
          hint3: 'P = 252/1024 = 63/256.',
          answer: 'A', level: 3,
        },
      ],

    },
  },

};
